---
title: "DD GRF RATE_Final4"
author: "PJH"
date: '2022-11-22'
output: html_document
---

```{r RATE No Brain: Total 1year}
rm(list=ls())
dd_data<-read.csv("C:\\Users\\socra\\Desktop\\Brain discounting\\Data\\ABCD Delay discounting merged_wide_kNN imputed dataset.csv", header=TRUE)

dd<-c('subjectkey', 'sex_0y', 'married_0y', 'income_0y', 'age_0y', 'race_g', 'race_ethnicity_0y', 'high_educ_0y', 'bmi_0y',
      'history_ratio_0y', 'abcd_site_0y', 'discount_rate_1y',
      'totalscore_pps_1y', 'totalscore_pps_2y', 'distress_score_pps_1y', 'distress_score_pps_2y',
      'section8_0y', 'rh_adi_perc1_0y', 'parent_age_0y', 'parent_identity_0y', 
      'JB_val_total_1y', 'nihtbx_totalcomp_uncorrected_0y',
      'cpeur2', 'eaeur1', 'depeur4', 'mddeur6', 'depmulti', 'bmieur4', 'bmimulti', 'iqeur2', 'insomniaeur6', 'snoringeur1',
      'happieur4', 'ghappieur2', 'ghappimeaneur1', 'ghappihealth6', 'alcdep_eurauto', 'alcdep_afrauto', 'alcdep_metaauto',
      'asdauto', 'aspauto', 'bipauto', 'cannabisauto', 'crossauto', 'drinkauto', 'edauto', 'neuroticismauto', 'ocdauto',
      'risk4pcauto', 'risktolauto', 'scz_eurauto', 'scz_easauto', 'scz_metaauto', 'smokerauto', 'worryauto', 'anxietyauto',
      'ptsdeur4', 'ptsdmeta6', 'adhdeur6', 'vol')


smri_data<-read.csv("C:\\Users\\socra\\Desktop\\Brain Discounting\\Data\\mor.some.qc.desikan.csv", header=TRUE)

MID_fMRI_data<-read.csv("C:\\Users\\socra\\Desktop\\Brain Discounting\\Data\\ABCD MID task fMRI Desikan_all_baseline.csv", header=TRUE)

MID_fMRI_data<-subset(data.frame(MID_fMRI_data), select = -c(eventname, interview_date, 
                                                             interview_age, sex, visit,
                                                             imgincl_t1w_include, imgincl_t2w_include, imgincl_dmri_include,
                                                             imgincl_rsfmri_include, imgincl_mid_include, imgincl_nback_include,
                                                             imgincl_sst_include, tfmri_mid_all_b_tr, tfmri_mid_all_b_numtrs,
                                                             tfmri_mid_all_b_dof, tfmri_mid_all_b_nvols, tfmri_mid_all_b_subthreshnvols, 
                                                             tfmri_mid_all_b_meanmotion, tfmri_mid_all_b_maxmotion, 
                                                             tfmri_mid_all_b_meantrans, tfmri_mid_all_b_maxtrans, tfmri_mid_all_b_meanrot,
                                                             tfmri_mid_all_b_maxrot))

dd_s<-dd_data[,dd]
MERGED1<-merge(dd_s, smri_data, by='subjectkey')
MERGED2<-merge(MERGED1, MID_fMRI_data, by='subjectkey')
data<-subset(MERGED2, JB_val_total_1y==1)
data<-na.omit(data)
# print("Sample Size=")
# print(nrow(data))


#########################Scale Continuous Variables#############################
#Structure MRI
# grep('lh_bankssts_area._.1', colnames(data))
# grep('CerebralWhiteMatterVol._.18', colnames(data))
data[, c(61:459)]<-scale(data.frame(data[, c(61:459)]))

#MID task fMRI
# grep('tfmri_ma_arvn_b_cds_clatcgelh', colnames(data))
# grep('tfmri_ma_alvsl_b_scs_vtdcrh', colnames(data))
data[, c(461:1439)]<-scale(data.frame(data[, c(461:1439)]))

#Other
contvar<-c("age_0y", "bmi_0y", "history_ratio_0y", 
       "income_0y", "high_educ_0y", "parent_age_0y", "vol", "rh_adi_perc1_0y",
       "discount_rate_1y", "totalscore_pps_1y", "totalscore_pps_2y", 
       "distress_score_pps_1y", "distress_score_pps_2y", "nihtbx_totalcomp_uncorrected_0y")

data[contvar]<-scale(data.frame(data[contvar]))


#################################Binary Treatment & Covariates######################################

data$rh_adi_bi_0y = ifelse(data$rh_adi_perc1_0y >= mean(data$rh_adi_perc1_0y), 1, 0)

# data$sex_0y<-as.factor(data$sex_0y)
# data$married_0y<-as.factor(data$married_0y)
# data$parent_identity_0y<-as.factor(data$parent_identity_0y)
# data$race_ethnicity_0y<-as.factor(data$race_ethnicity_0y)


library(fastDummies)

data<-dummy_cols(data, select_columns = c('sex_0y', 'married_0y', 'race_g', 'parent_identity_0y', 'race_ethnicity_0y'))


library(learnr)
library(DiagrammeR)
library(grf)
library(tidyverse)
library(broom)
library(fastDummies)
library(lmtest)
library(rpart)
library(glmnet)
library(splines)
library(MASS)
library(sandwich)
library(ggplot2)
library(data.table)

covariates<-c('discount_rate_1y','age_0y', 'bmi_0y', 'income_0y', 
                 'high_educ_0y', 'sex_0y_F', 
                 'married_0y_2', 'married_0y_3', 'married_0y_4', 'married_0y_5', 'married_0y_6',
                 'parent_identity_0y_2','parent_identity_0y_3', 
                 'parent_identity_0y_4', 'parent_identity_0y_5',
                 'race_ethnicity_0y_2', 'race_ethnicity_0y_3', 
                 'race_ethnicity_0y_4', 'race_ethnicity_0y_5',
                 'parent_age_0y', 
                 'cpeur2', 'eaeur1', 'iqeur2',
                 'nihtbx_totalcomp_uncorrected_0y', 'history_ratio_0y')

W = data$rh_adi_bi_0y
X = data[, covariates]
Z = data$section8_0y
n = nrow(data)
  
################## RATE: Total Score PLE 1year #######################

Y <- data[, 'totalscore_pps_1y']

train <- sample(1:n, n/2)

set.seed(123, kind = "Mersenne-Twister", normal.kind = "Inversion", sample.kind = "Rejection")
cf.priority <- instrumental_forest(
    X[train, ], Y[train], W[train], Z[train],
    num.trees = 40000, 
    tune.parameters = 'all',
    tune.num.trees = 5000,
    tune.num.reps = 250,
    tune.num.draws = 4500)

set.seed(123, kind = "Mersenne-Twister", normal.kind = "Inversion", sample.kind = "Rejection")
# Estimate AUTOC on held out data.
cf.eval <- instrumental_forest(
  X[-train, ], Y[-train], W[-train], Z[-train], 
  num.trees = 40000, 
    tune.parameters = 'all',
    tune.num.trees = 5000,
    tune.num.reps = 250,
    tune.num.draws = 4500)


set.seed(123, kind = "Mersenne-Twister", normal.kind = "Inversion", sample.kind = "Rejection")
tau.hat <- predict(cf.priority, X[-train, ])$predictions
rate <- rank_average_treatment_effect(cf.eval, tau.hat, target = "AUTOC")


est<-rate$estimate
se<-rate$std.err
tstat <- est / se
pvalue <- 2*(1-pnorm(abs(tstat)))
lowci<- est + -1 * qnorm(0.975) * se 
highci<- est + 1 * qnorm(0.975) * se 
rate.res<-cbind(est, se, tstat, pvalue, lowci, highci)
row.names(rate.res)<-'RATE: Total Score PLE 1year'
print(rate.res)


plot(rate, xlab = "Treated fraction", main = "TOC of Total PLEs (1year) evaluated on ATE estimated from 50% Sample Size")  
  
```



```{r RATE No Brain: Distress 1year}
rm(list=ls())
dd_data<-read.csv("C:\\Users\\socra\\Desktop\\Brain discounting\\Data\\ABCD Delay discounting merged_wide_kNN imputed dataset.csv", header=TRUE)

dd<-c('subjectkey', 'sex_0y', 'married_0y', 'income_0y', 'age_0y', 'race_g', 'race_ethnicity_0y', 'high_educ_0y', 'bmi_0y',
      'history_ratio_0y', 'abcd_site_0y', 'discount_rate_1y',
      'totalscore_pps_1y', 'totalscore_pps_2y', 'distress_score_pps_1y', 'distress_score_pps_2y',
      'section8_0y', 'rh_adi_perc1_0y', 'parent_age_0y', 'parent_identity_0y', 
      'JB_val_total_1y', 'nihtbx_totalcomp_uncorrected_0y',
      'cpeur2', 'eaeur1', 'depeur4', 'mddeur6', 'depmulti', 'bmieur4', 'bmimulti', 'iqeur2', 'insomniaeur6', 'snoringeur1',
      'happieur4', 'ghappieur2', 'ghappimeaneur1', 'ghappihealth6', 'alcdep_eurauto', 'alcdep_afrauto', 'alcdep_metaauto',
      'asdauto', 'aspauto', 'bipauto', 'cannabisauto', 'crossauto', 'drinkauto', 'edauto', 'neuroticismauto', 'ocdauto',
      'risk4pcauto', 'risktolauto', 'scz_eurauto', 'scz_easauto', 'scz_metaauto', 'smokerauto', 'worryauto', 'anxietyauto',
      'ptsdeur4', 'ptsdmeta6', 'adhdeur6', 'vol')


smri_data<-read.csv("C:\\Users\\socra\\Desktop\\Brain Discounting\\Data\\mor.some.qc.desikan.csv", header=TRUE)

MID_fMRI_data<-read.csv("C:\\Users\\socra\\Desktop\\Brain Discounting\\Data\\ABCD MID task fMRI Desikan_all_baseline.csv", header=TRUE)

MID_fMRI_data<-subset(data.frame(MID_fMRI_data), select = -c(eventname, interview_date, 
                                                             interview_age, sex, visit,
                                                             imgincl_t1w_include, imgincl_t2w_include, imgincl_dmri_include,
                                                             imgincl_rsfmri_include, imgincl_mid_include, imgincl_nback_include,
                                                             imgincl_sst_include, tfmri_mid_all_b_tr, tfmri_mid_all_b_numtrs,
                                                             tfmri_mid_all_b_dof, tfmri_mid_all_b_nvols, tfmri_mid_all_b_subthreshnvols, 
                                                             tfmri_mid_all_b_meanmotion, tfmri_mid_all_b_maxmotion, 
                                                             tfmri_mid_all_b_meantrans, tfmri_mid_all_b_maxtrans, tfmri_mid_all_b_meanrot,
                                                             tfmri_mid_all_b_maxrot))

dd_s<-dd_data[,dd]
MERGED1<-merge(dd_s, smri_data, by='subjectkey')
MERGED2<-merge(MERGED1, MID_fMRI_data, by='subjectkey')
data<-subset(MERGED2, JB_val_total_1y==1)
data<-na.omit(data)
# print("Sample Size=")
# print(nrow(data))


#########################Scale Continuous Variables#############################
#Structure MRI
# grep('lh_bankssts_area._.1', colnames(data))
# grep('CerebralWhiteMatterVol._.18', colnames(data))
data[, c(61:459)]<-scale(data.frame(data[, c(61:459)]))

#MID task fMRI
# grep('tfmri_ma_arvn_b_cds_clatcgelh', colnames(data))
# grep('tfmri_ma_alvsl_b_scs_vtdcrh', colnames(data))
data[, c(461:1439)]<-scale(data.frame(data[, c(461:1439)]))

#Other
contvar<-c("age_0y", "bmi_0y", "history_ratio_0y", 
       "income_0y", "high_educ_0y", "parent_age_0y", "vol", "rh_adi_perc1_0y",
       "discount_rate_1y", "totalscore_pps_1y", "totalscore_pps_2y", 
       "distress_score_pps_1y", "distress_score_pps_2y", "nihtbx_totalcomp_uncorrected_0y")

data[contvar]<-scale(data.frame(data[contvar]))


#################################Binary Treatment & Covariates######################################

data$rh_adi_bi_0y = ifelse(data$rh_adi_perc1_0y >= mean(data$rh_adi_perc1_0y), 1, 0)

# data$sex_0y<-as.factor(data$sex_0y)
# data$married_0y<-as.factor(data$married_0y)
# data$parent_identity_0y<-as.factor(data$parent_identity_0y)
# data$race_ethnicity_0y<-as.factor(data$race_ethnicity_0y)


library(fastDummies)

data<-dummy_cols(data, select_columns = c('sex_0y', 'married_0y', 'race_g', 'parent_identity_0y', 'race_ethnicity_0y'))


library(learnr)
library(DiagrammeR)
library(grf)
library(tidyverse)
library(broom)
library(fastDummies)
library(lmtest)
library(rpart)
library(glmnet)
library(splines)
library(MASS)
library(sandwich)
library(ggplot2)
library(data.table)

covariates<-c('discount_rate_1y','age_0y', 'bmi_0y', 'income_0y', 
                 'high_educ_0y', 'sex_0y_F', 
                 'married_0y_2', 'married_0y_3', 'married_0y_4', 'married_0y_5', 'married_0y_6',
                 'parent_identity_0y_2','parent_identity_0y_3', 
                 'parent_identity_0y_4', 'parent_identity_0y_5',
                 'race_ethnicity_0y_2', 'race_ethnicity_0y_3', 
                 'race_ethnicity_0y_4', 'race_ethnicity_0y_5',
                 'parent_age_0y', 
                 'cpeur2', 'eaeur1', 'iqeur2',
                 'nihtbx_totalcomp_uncorrected_0y', 'history_ratio_0y')

W = data$rh_adi_bi_0y
X = data[, covariates]
Z = data$section8_0y
n = nrow(data)

  
################## RATE: Distress Score PLE 1year #######################
Y <- data[, 'distress_score_pps_1y']

train <- sample(1:n, n/2)

set.seed(123, kind = "Mersenne-Twister", normal.kind = "Inversion", sample.kind = "Rejection")
cf.priority <- instrumental_forest(
  X[train, ], Y[train], W[train], Z[train],
  num.trees = 40000, 
  tune.parameters = 'all',
  tune.num.trees = 5000,
  tune.num.reps = 200,
  tune.num.draws = 4000)

set.seed(123, kind = "Mersenne-Twister", normal.kind = "Inversion", sample.kind = "Rejection")
# Estimate AUTOC on held out data.
cf.eval <- instrumental_forest(
  X[-train, ], Y[-train], W[-train], Z[-train], 
  num.trees = 40000, 
  tune.parameters = 'all',
  tune.num.trees = 5000,
  tune.num.reps = 200,
  tune.num.draws = 4000)


set.seed(123, kind = "Mersenne-Twister", normal.kind = "Inversion", sample.kind = "Rejection")
tau.hat <- predict(cf.priority, X[-train, ])$predictions
rate <- rank_average_treatment_effect(cf.eval, tau.hat, target = "AUTOC")

est<-rate$estimate
se<-rate$std.err
tstat <- est / se
pvalue <- 2*(1-pnorm(abs(tstat)))
lowci<- est + -1 * qnorm(0.975) * se 
highci<- est + 1 * qnorm(0.975) * se 
rate.res<-cbind(est, se, tstat, pvalue, lowci, highci)
row.names(rate.res)<-'RATE: Distress PLEs 1y'
print(rate.res)



plot(rate, xlab = "Treated fraction", main = "TOC of Distress PLEs (1year) evaluated on ATE estimated from 50% Sample Size")  
  
  
```


```{r RATE No Brain: Total 2year}
rm(list=ls())
dd_data<-read.csv("C:\\Users\\socra\\Desktop\\Brain discounting\\Data\\ABCD Delay discounting merged_wide_kNN imputed dataset.csv", header=TRUE)

dd<-c('subjectkey', 'sex_0y', 'married_0y', 'income_0y', 'age_0y', 'race_g', 'race_ethnicity_0y', 'high_educ_0y', 'bmi_0y',
      'history_ratio_0y', 'abcd_site_0y', 'discount_rate_1y',
      'totalscore_pps_1y', 'totalscore_pps_2y', 'distress_score_pps_1y', 'distress_score_pps_2y',
      'section8_0y', 'rh_adi_perc1_0y', 'parent_age_0y', 'parent_identity_0y', 
      'JB_val_total_1y', 'nihtbx_totalcomp_uncorrected_0y',
      'cpeur2', 'eaeur1', 'depeur4', 'mddeur6', 'depmulti', 'bmieur4', 'bmimulti', 'iqeur2', 'insomniaeur6', 'snoringeur1',
      'happieur4', 'ghappieur2', 'ghappimeaneur1', 'ghappihealth6', 'alcdep_eurauto', 'alcdep_afrauto', 'alcdep_metaauto',
      'asdauto', 'aspauto', 'bipauto', 'cannabisauto', 'crossauto', 'drinkauto', 'edauto', 'neuroticismauto', 'ocdauto',
      'risk4pcauto', 'risktolauto', 'scz_eurauto', 'scz_easauto', 'scz_metaauto', 'smokerauto', 'worryauto', 'anxietyauto',
      'ptsdeur4', 'ptsdmeta6', 'adhdeur6', 'vol')


smri_data<-read.csv("C:\\Users\\socra\\Desktop\\Brain Discounting\\Data\\mor.some.qc.desikan.csv", header=TRUE)

MID_fMRI_data<-read.csv("C:\\Users\\socra\\Desktop\\Brain Discounting\\Data\\ABCD MID task fMRI Desikan_all_baseline.csv", header=TRUE)

MID_fMRI_data<-subset(data.frame(MID_fMRI_data), select = -c(eventname, interview_date, 
                                                             interview_age, sex, visit,
                                                             imgincl_t1w_include, imgincl_t2w_include, imgincl_dmri_include,
                                                             imgincl_rsfmri_include, imgincl_mid_include, imgincl_nback_include,
                                                             imgincl_sst_include, tfmri_mid_all_b_tr, tfmri_mid_all_b_numtrs,
                                                             tfmri_mid_all_b_dof, tfmri_mid_all_b_nvols, tfmri_mid_all_b_subthreshnvols, 
                                                             tfmri_mid_all_b_meanmotion, tfmri_mid_all_b_maxmotion, 
                                                             tfmri_mid_all_b_meantrans, tfmri_mid_all_b_maxtrans, tfmri_mid_all_b_meanrot,
                                                             tfmri_mid_all_b_maxrot))

dd_s<-dd_data[,dd]
MERGED1<-merge(dd_s, smri_data, by='subjectkey')
MERGED2<-merge(MERGED1, MID_fMRI_data, by='subjectkey')
data<-subset(MERGED2, JB_val_total_1y==1)
data<-na.omit(data)
# print("Sample Size=")
# print(nrow(data))


#########################Scale Continuous Variables#############################
#Structure MRI
# grep('lh_bankssts_area._.1', colnames(data))
# grep('CerebralWhiteMatterVol._.18', colnames(data))
data[, c(61:459)]<-scale(data.frame(data[, c(61:459)]))

#MID task fMRI
# grep('tfmri_ma_arvn_b_cds_clatcgelh', colnames(data))
# grep('tfmri_ma_alvsl_b_scs_vtdcrh', colnames(data))
data[, c(461:1439)]<-scale(data.frame(data[, c(461:1439)]))

#Other
contvar<-c("age_0y", "bmi_0y", "history_ratio_0y", 
       "income_0y", "high_educ_0y", "parent_age_0y", "vol", "rh_adi_perc1_0y",
       "discount_rate_1y", "totalscore_pps_1y", "totalscore_pps_2y", 
       "distress_score_pps_1y", "distress_score_pps_2y", "nihtbx_totalcomp_uncorrected_0y")

data[contvar]<-scale(data.frame(data[contvar]))


#################################Binary Treatment & Covariates######################################

data$rh_adi_bi_0y = ifelse(data$rh_adi_perc1_0y >= mean(data$rh_adi_perc1_0y), 1, 0)

# data$sex_0y<-as.factor(data$sex_0y)
# data$married_0y<-as.factor(data$married_0y)
# data$parent_identity_0y<-as.factor(data$parent_identity_0y)
# data$race_ethnicity_0y<-as.factor(data$race_ethnicity_0y)


library(fastDummies)

data<-dummy_cols(data, select_columns = c('sex_0y', 'married_0y', 'race_g', 'parent_identity_0y', 'race_ethnicity_0y'))


library(learnr)
library(DiagrammeR)
library(grf)
library(tidyverse)
library(broom)
library(fastDummies)
library(lmtest)
library(rpart)
library(glmnet)
library(splines)
library(MASS)
library(sandwich)
library(ggplot2)
library(data.table)

covariates<-c('discount_rate_1y','age_0y', 'bmi_0y', 'income_0y', 
                 'high_educ_0y', 'sex_0y_F', 
                 'married_0y_2', 'married_0y_3', 'married_0y_4', 'married_0y_5', 'married_0y_6',
                 'parent_identity_0y_2','parent_identity_0y_3', 
                 'parent_identity_0y_4', 'parent_identity_0y_5',
                 'race_ethnicity_0y_2', 'race_ethnicity_0y_3', 
                 'race_ethnicity_0y_4', 'race_ethnicity_0y_5',
                 'parent_age_0y', 
                 'cpeur2', 'eaeur1', 'iqeur2',
                 'nihtbx_totalcomp_uncorrected_0y', 'history_ratio_0y')

W = data$rh_adi_bi_0y
X = data[, covariates]
Z = data$section8_0y
n = nrow(data)
  
################## RATE: Total Score PLE 2year #######################

Y <- data[, 'totalscore_pps_2y']

train <- sample(1:n, n/2)

set.seed(123, kind = "Mersenne-Twister", normal.kind = "Inversion", sample.kind = "Rejection")
cf.priority <- instrumental_forest(
    X[train, ], Y[train], W[train], Z[train],
    num.trees = 40000, 
    tune.parameters = 'all',
    tune.num.trees = 5000,
    tune.num.reps = 250,
    tune.num.draws = 4500)

set.seed(123, kind = "Mersenne-Twister", normal.kind = "Inversion", sample.kind = "Rejection")
# Estimate AUTOC on held out data.
cf.eval <- instrumental_forest(
  X[-train, ], Y[-train], W[-train], Z[-train], 
  num.trees = 40000, 
    tune.parameters = 'all',
    tune.num.trees = 5000,
    tune.num.reps = 250,
    tune.num.draws = 4500)


set.seed(123, kind = "Mersenne-Twister", normal.kind = "Inversion", sample.kind = "Rejection")
tau.hat <- predict(cf.priority, X[-train, ])$predictions
rate <- rank_average_treatment_effect(cf.eval, tau.hat, target = "AUTOC")


est<-rate$estimate
se<-rate$std.err
tstat <- est / se
pvalue <- 2*(1-pnorm(abs(tstat)))
lowci<- est + -1 * qnorm(0.975) * se 
highci<- est + 1 * qnorm(0.975) * se 
rate.res<-cbind(est, se, tstat, pvalue, lowci, highci)
row.names(rate.res)<-'RATE: Total Score PLE 2year'
print(rate.res)


plot(rate, xlab = "Treated fraction", main = "TOC of Total PLEs (2year) evaluated on ATE estimated from 50% Sample Size")  
  
```




```{r RATE No Brain: Distress 2year}
rm(list=ls())
dd_data<-read.csv("C:\\Users\\socra\\Desktop\\Brain discounting\\Data\\ABCD Delay discounting merged_wide_kNN imputed dataset.csv", header=TRUE)

dd<-c('subjectkey', 'sex_0y', 'married_0y', 'income_0y', 'age_0y', 'race_g', 'race_ethnicity_0y', 'high_educ_0y', 'bmi_0y',
      'history_ratio_0y', 'abcd_site_0y', 'discount_rate_1y',
      'totalscore_pps_1y', 'totalscore_pps_2y', 'distress_score_pps_1y', 'distress_score_pps_2y',
      'section8_0y', 'rh_adi_perc1_0y', 'parent_age_0y', 'parent_identity_0y', 
      'JB_val_total_1y', 'nihtbx_totalcomp_uncorrected_0y',
      'cpeur2', 'eaeur1', 'depeur4', 'mddeur6', 'depmulti', 'bmieur4', 'bmimulti', 'iqeur2', 'insomniaeur6', 'snoringeur1',
      'happieur4', 'ghappieur2', 'ghappimeaneur1', 'ghappihealth6', 'alcdep_eurauto', 'alcdep_afrauto', 'alcdep_metaauto',
      'asdauto', 'aspauto', 'bipauto', 'cannabisauto', 'crossauto', 'drinkauto', 'edauto', 'neuroticismauto', 'ocdauto',
      'risk4pcauto', 'risktolauto', 'scz_eurauto', 'scz_easauto', 'scz_metaauto', 'smokerauto', 'worryauto', 'anxietyauto',
      'ptsdeur4', 'ptsdmeta6', 'adhdeur6', 'vol')


smri_data<-read.csv("C:\\Users\\socra\\Desktop\\Brain Discounting\\Data\\mor.some.qc.desikan.csv", header=TRUE)

MID_fMRI_data<-read.csv("C:\\Users\\socra\\Desktop\\Brain Discounting\\Data\\ABCD MID task fMRI Desikan_all_baseline.csv", header=TRUE)

MID_fMRI_data<-subset(data.frame(MID_fMRI_data), select = -c(eventname, interview_date, 
                                                             interview_age, sex, visit,
                                                             imgincl_t1w_include, imgincl_t2w_include, imgincl_dmri_include,
                                                             imgincl_rsfmri_include, imgincl_mid_include, imgincl_nback_include,
                                                             imgincl_sst_include, tfmri_mid_all_b_tr, tfmri_mid_all_b_numtrs,
                                                             tfmri_mid_all_b_dof, tfmri_mid_all_b_nvols, tfmri_mid_all_b_subthreshnvols, 
                                                             tfmri_mid_all_b_meanmotion, tfmri_mid_all_b_maxmotion, 
                                                             tfmri_mid_all_b_meantrans, tfmri_mid_all_b_maxtrans, tfmri_mid_all_b_meanrot,
                                                             tfmri_mid_all_b_maxrot))

dd_s<-dd_data[,dd]
MERGED1<-merge(dd_s, smri_data, by='subjectkey')
MERGED2<-merge(MERGED1, MID_fMRI_data, by='subjectkey')
data<-subset(MERGED2, JB_val_total_1y==1)
data<-na.omit(data)
# print("Sample Size=")
# print(nrow(data))


#########################Scale Continuous Variables#############################
#Structure MRI
# grep('lh_bankssts_area._.1', colnames(data))
# grep('CerebralWhiteMatterVol._.18', colnames(data))
data[, c(61:459)]<-scale(data.frame(data[, c(61:459)]))

#MID task fMRI
# grep('tfmri_ma_arvn_b_cds_clatcgelh', colnames(data))
# grep('tfmri_ma_alvsl_b_scs_vtdcrh', colnames(data))
data[, c(461:1439)]<-scale(data.frame(data[, c(461:1439)]))

#Other
contvar<-c("age_0y", "bmi_0y", "history_ratio_0y", 
       "income_0y", "high_educ_0y", "parent_age_0y", "vol", "rh_adi_perc1_0y",
       "discount_rate_1y", "totalscore_pps_1y", "totalscore_pps_2y", 
       "distress_score_pps_1y", "distress_score_pps_2y", "nihtbx_totalcomp_uncorrected_0y")

data[contvar]<-scale(data.frame(data[contvar]))


#################################Binary Treatment & Covariates######################################

data$rh_adi_bi_0y = ifelse(data$rh_adi_perc1_0y >= mean(data$rh_adi_perc1_0y), 1, 0)

# data$sex_0y<-as.factor(data$sex_0y)
# data$married_0y<-as.factor(data$married_0y)
# data$parent_identity_0y<-as.factor(data$parent_identity_0y)
# data$race_ethnicity_0y<-as.factor(data$race_ethnicity_0y)


library(fastDummies)

data<-dummy_cols(data, select_columns = c('sex_0y', 'married_0y', 'race_g', 'parent_identity_0y', 'race_ethnicity_0y'))


library(learnr)
library(DiagrammeR)
library(grf)
library(tidyverse)
library(broom)
library(fastDummies)
library(lmtest)
library(rpart)
library(glmnet)
library(splines)
library(MASS)
library(sandwich)
library(ggplot2)
library(data.table)

covariates<-c('discount_rate_1y','age_0y', 'bmi_0y', 'income_0y', 
                 'high_educ_0y', 'sex_0y_F', 
                 'married_0y_2', 'married_0y_3', 'married_0y_4', 'married_0y_5', 'married_0y_6',
                 'parent_identity_0y_2','parent_identity_0y_3', 
                 'parent_identity_0y_4', 'parent_identity_0y_5',
                 'race_ethnicity_0y_2', 'race_ethnicity_0y_3', 
                 'race_ethnicity_0y_4', 'race_ethnicity_0y_5',
                 'parent_age_0y', 
                 'cpeur2', 'eaeur1', 'iqeur2',
                 'nihtbx_totalcomp_uncorrected_0y', 'history_ratio_0y')

W = data$rh_adi_bi_0y
X = data[, covariates]
Z = data$section8_0y
n = nrow(data)

  
################## RATE: Distress Score PLE 2year #######################
Y <- data[, 'distress_score_pps_2y']

train <- sample(1:n, n/2)

set.seed(123, kind = "Mersenne-Twister", normal.kind = "Inversion", sample.kind = "Rejection")
cf.priority <- instrumental_forest(
  X[train, ], Y[train], W[train], Z[train],
  num.trees = 40000, 
  tune.parameters = 'all',
  tune.num.trees = 5000,
  tune.num.reps = 200,
  tune.num.draws = 4000)

set.seed(123, kind = "Mersenne-Twister", normal.kind = "Inversion", sample.kind = "Rejection")
# Estimate AUTOC on held out data.
cf.eval <- instrumental_forest(
  X[-train, ], Y[-train], W[-train], Z[-train], 
  num.trees = 40000, 
  tune.parameters = 'all',
  tune.num.trees = 5000,
  tune.num.reps = 200,
  tune.num.draws = 4000)


set.seed(123, kind = "Mersenne-Twister", normal.kind = "Inversion", sample.kind = "Rejection")
tau.hat <- predict(cf.priority, X[-train, ])$predictions
rate <- rank_average_treatment_effect(cf.eval, tau.hat, target = "AUTOC")

est<-rate$estimate
se<-rate$std.err
tstat <- est / se
pvalue <- 2*(1-pnorm(abs(tstat)))
lowci<- est + -1 * qnorm(0.975) * se 
highci<- est + 1 * qnorm(0.975) * se 
rate.res<-cbind(est, se, tstat, pvalue, lowci, highci)
row.names(rate.res)<-'RATE: Distress PLEs 2y'
print(rate.res)



plot(rate, xlab = "Treated fraction", main = "TOC of Distress PLEs (2year) evaluated on ATE estimated from 50% Sample Size")  
  
  
```




```{r RATE Brain: Total 1year}
rm(list=ls())
dd_data<-read.csv("C:\\Users\\socra\\Desktop\\Brain discounting\\Data\\ABCD Delay discounting merged_wide_kNN imputed dataset.csv", header=TRUE)

dd<-c('subjectkey', 'sex_0y', 'married_0y', 'income_0y', 'age_0y', 'race_g', 'race_ethnicity_0y', 'high_educ_0y', 'bmi_0y',
      'history_ratio_0y', 'abcd_site_0y', 'discount_rate_1y',
      'totalscore_pps_1y', 'totalscore_pps_2y', 'distress_score_pps_1y', 'distress_score_pps_2y',
      'section8_0y', 'rh_adi_perc1_0y', 'parent_age_0y', 'parent_identity_0y', 
      'JB_val_total_1y', 'nihtbx_totalcomp_uncorrected_0y',
      'cpeur2', 'eaeur1', 'depeur4', 'mddeur6', 'depmulti', 'bmieur4', 'bmimulti', 'iqeur2', 'insomniaeur6', 'snoringeur1',
      'happieur4', 'ghappieur2', 'ghappimeaneur1', 'ghappihealth6', 'alcdep_eurauto', 'alcdep_afrauto', 'alcdep_metaauto',
      'asdauto', 'aspauto', 'bipauto', 'cannabisauto', 'crossauto', 'drinkauto', 'edauto', 'neuroticismauto', 'ocdauto',
      'risk4pcauto', 'risktolauto', 'scz_eurauto', 'scz_easauto', 'scz_metaauto', 'smokerauto', 'worryauto', 'anxietyauto',
      'ptsdeur4', 'ptsdmeta6', 'adhdeur6', 'vol')


smri_data<-read.csv("C:\\Users\\socra\\Desktop\\Brain Discounting\\Data\\mor.some.qc.desikan.csv", header=TRUE)

MID_fMRI_data<-read.csv("C:\\Users\\socra\\Desktop\\Brain Discounting\\Data\\ABCD MID task fMRI Desikan_all_baseline.csv", header=TRUE)

MID_fMRI_data<-subset(data.frame(MID_fMRI_data), select = -c(eventname, interview_date, 
                                                             interview_age, sex, visit,
                                                             imgincl_t1w_include, imgincl_t2w_include, imgincl_dmri_include,
                                                             imgincl_rsfmri_include, imgincl_mid_include, imgincl_nback_include,
                                                             imgincl_sst_include, tfmri_mid_all_b_tr, tfmri_mid_all_b_numtrs,
                                                             tfmri_mid_all_b_dof, tfmri_mid_all_b_nvols, tfmri_mid_all_b_subthreshnvols, 
                                                             tfmri_mid_all_b_meanmotion, tfmri_mid_all_b_maxmotion, 
                                                             tfmri_mid_all_b_meantrans, tfmri_mid_all_b_maxtrans, tfmri_mid_all_b_meanrot,
                                                             tfmri_mid_all_b_maxrot))

dd_s<-dd_data[,dd]
MERGED1<-merge(dd_s, smri_data, by='subjectkey')
MERGED2<-merge(MERGED1, MID_fMRI_data, by='subjectkey')
data<-subset(MERGED2, JB_val_total_1y==1)
data<-na.omit(data)
# print("Sample Size=")
# print(nrow(data))


#########################Scale Continuous Variables#############################
#Structure MRI
# grep('lh_bankssts_area._.1', colnames(data))
# grep('CerebralWhiteMatterVol._.18', colnames(data))
data[, c(61:459)]<-scale(data.frame(data[, c(61:459)]))

#MID task fMRI
# grep('tfmri_ma_arvn_b_cds_clatcgelh', colnames(data))
# grep('tfmri_ma_alvsl_b_scs_vtdcrh', colnames(data))
data[, c(461:1439)]<-scale(data.frame(data[, c(461:1439)]))

#Other
contvar<-c("age_0y", "bmi_0y", "history_ratio_0y", 
       "income_0y", "high_educ_0y", "parent_age_0y", "vol", "rh_adi_perc1_0y",
       "discount_rate_1y", "totalscore_pps_1y", "totalscore_pps_2y", 
       "distress_score_pps_1y", "distress_score_pps_2y", "nihtbx_totalcomp_uncorrected_0y")

data[contvar]<-scale(data.frame(data[contvar]))


#################################Binary Treatment & Covariates######################################

data$rh_adi_bi_0y = ifelse(data$rh_adi_perc1_0y >= mean(data$rh_adi_perc1_0y), 1, 0)

# data$sex_0y<-as.factor(data$sex_0y)
# data$married_0y<-as.factor(data$married_0y)
# data$parent_identity_0y<-as.factor(data$parent_identity_0y)
# data$race_ethnicity_0y<-as.factor(data$race_ethnicity_0y)


library(fastDummies)

data<-dummy_cols(data, select_columns = c('sex_0y', 'married_0y', 'race_g', 'parent_identity_0y', 'race_ethnicity_0y'))


library(learnr)
library(DiagrammeR)
library(grf)
library(tidyverse)
library(broom)
library(fastDummies)
library(lmtest)
library(rpart)
library(glmnet)
library(splines)
library(MASS)
library(sandwich)
library(ggplot2)
library(data.table)

covariates<-c('discount_rate_1y','age_0y', 'bmi_0y', 'income_0y', 
                 'high_educ_0y', 'sex_0y_F', 'vol',
                 'married_0y_2', 'married_0y_3', 'married_0y_4', 'married_0y_5', 'married_0y_6',
                 'parent_identity_0y_2','parent_identity_0y_3', 
                 'parent_identity_0y_4', 'parent_identity_0y_5',
                 'race_ethnicity_0y_2', 'race_ethnicity_0y_3', 
                 'race_ethnicity_0y_4', 'race_ethnicity_0y_5',
                 'parent_age_0y', 
                 'cpeur2', 'eaeur1', 'iqeur2',
                 'nihtbx_totalcomp_uncorrected_0y', 'history_ratio_0y',
                'lh_rostralanteriorcingulate_area._.1', 'lh_WhiteSurfArea_area._.1', 'rh_isthmuscingulate_area._.2',
              'rh_parahippocampal_area._.2', 'rh_parsopercularis_area._.2', 'rh_temporalpole_area._.2', 
              'rh_fusiform_volume._.8', 'rh_parahippocampal_volume._.8', 'rh_parsopercularis_volume._.8', 
              'Right.Caudate._.9', 'TotalGrayVol._.9', 'wm.rh.temporalpole._.18',
              'tfmri_ma_arvn_b_cds_smglh', 'tfmri_ma_arvn_b_cds_pocgerh', 'tfmri_ma_acvn_b_cds_pcelh', 
              'tfmri_ma_acvn_b_cds_prgisrh', 'tfmri_ma_acvn_b_cds_pocgerh', 'tfmri_ma_alrvn_b_cds_postcrh', 
              'tfmri_ma_alrvn_b_cds_romdfrrh', 'tfmri_ma_asrvn_b_cds_smglh', 'tfmri_ma_asrvn_b_cds_smgrh', 
              'tfmri_ma_allvn_b_cds_tvtplh', 'tfmri_ma_allvn_b_cds_ffrh', 'tfmri_ma_asvn_b_cds_smgrh', 
              'tfmri_ma_acmvn_b_scs_cbwmrh')

W = data$rh_adi_bi_0y
X = data[, covariates]
Z = data$section8_0y
n = nrow(data)


  
################## RATE: Total Score PLE 1year #######################

Y <- data[, 'totalscore_pps_1y']

train <- sample(1:n, n/2)

set.seed(123, kind = "Mersenne-Twister", normal.kind = "Inversion", sample.kind = "Rejection")
cf.priority <- instrumental_forest(
    X[train, ], Y[train], W[train], Z[train],
    num.trees = 40000, 
    tune.parameters = 'all',
    tune.num.trees = 5000,
    tune.num.reps = 250,
    tune.num.draws = 4000)

set.seed(123, kind = "Mersenne-Twister", normal.kind = "Inversion", sample.kind = "Rejection")
# Estimate AUTOC on held out data.
cf.eval <- instrumental_forest(
  X[-train, ], Y[-train], W[-train], Z[-train], 
  num.trees = 40000, 
  tune.parameters = 'all',
  tune.num.trees = 5000,
  tune.num.reps = 250,
  tune.num.draws = 4000)


set.seed(123, kind = "Mersenne-Twister", normal.kind = "Inversion", sample.kind = "Rejection")
tau.hat <- predict(cf.priority, X[-train, ])$predictions
rate <- rank_average_treatment_effect(cf.eval, tau.hat, target = "AUTOC")


est<-rate$estimate
se<-rate$std.err
tstat <- est / se
pvalue <- 2*(1-pnorm(abs(tstat)))
lowci<- est + -1 * qnorm(0.975) * se 
highci<- est + 1 * qnorm(0.975) * se 
rate.res<-cbind(est, se, tstat, pvalue, lowci, highci)
row.names(rate.res)<-'RATE: Total Score PLE 1year'
print(rate.res)


pdf(file="totalscore_1y_RATE_brain.pdf", width=8, height=6)
plot(rate, xlab = "Treated fraction", main = "TOC of Total PLEs (1year) evaluated on ATE estimated from 50% Sample Size")  
dev.off()
  
```




```{r RATE Brain: Distress 1year}
rm(list=ls())
dd_data<-read.csv("C:\\Users\\socra\\Desktop\\Brain discounting\\Data\\ABCD Delay discounting merged_wide_kNN imputed dataset.csv", header=TRUE)

dd<-c('subjectkey', 'sex_0y', 'married_0y', 'income_0y', 'age_0y', 'race_g', 'race_ethnicity_0y', 'high_educ_0y', 'bmi_0y',
      'history_ratio_0y', 'abcd_site_0y', 'discount_rate_1y',
      'totalscore_pps_1y', 'totalscore_pps_2y', 'distress_score_pps_1y', 'distress_score_pps_2y',
      'section8_0y', 'rh_adi_perc1_0y', 'parent_age_0y', 'parent_identity_0y', 
      'JB_val_total_1y', 'nihtbx_totalcomp_uncorrected_0y',
      'cpeur2', 'eaeur1', 'depeur4', 'mddeur6', 'depmulti', 'bmieur4', 'bmimulti', 'iqeur2', 'insomniaeur6', 'snoringeur1',
      'happieur4', 'ghappieur2', 'ghappimeaneur1', 'ghappihealth6', 'alcdep_eurauto', 'alcdep_afrauto', 'alcdep_metaauto',
      'asdauto', 'aspauto', 'bipauto', 'cannabisauto', 'crossauto', 'drinkauto', 'edauto', 'neuroticismauto', 'ocdauto',
      'risk4pcauto', 'risktolauto', 'scz_eurauto', 'scz_easauto', 'scz_metaauto', 'smokerauto', 'worryauto', 'anxietyauto',
      'ptsdeur4', 'ptsdmeta6', 'adhdeur6', 'vol')


smri_data<-read.csv("C:\\Users\\socra\\Desktop\\Brain Discounting\\Data\\mor.some.qc.desikan.csv", header=TRUE)

MID_fMRI_data<-read.csv("C:\\Users\\socra\\Desktop\\Brain Discounting\\Data\\ABCD MID task fMRI Desikan_all_baseline.csv", header=TRUE)

MID_fMRI_data<-subset(data.frame(MID_fMRI_data), select = -c(eventname, interview_date, 
                                                             interview_age, sex, visit,
                                                             imgincl_t1w_include, imgincl_t2w_include, imgincl_dmri_include,
                                                             imgincl_rsfmri_include, imgincl_mid_include, imgincl_nback_include,
                                                             imgincl_sst_include, tfmri_mid_all_b_tr, tfmri_mid_all_b_numtrs,
                                                             tfmri_mid_all_b_dof, tfmri_mid_all_b_nvols, tfmri_mid_all_b_subthreshnvols, 
                                                             tfmri_mid_all_b_meanmotion, tfmri_mid_all_b_maxmotion, 
                                                             tfmri_mid_all_b_meantrans, tfmri_mid_all_b_maxtrans, tfmri_mid_all_b_meanrot,
                                                             tfmri_mid_all_b_maxrot))

dd_s<-dd_data[,dd]
MERGED1<-merge(dd_s, smri_data, by='subjectkey')
MERGED2<-merge(MERGED1, MID_fMRI_data, by='subjectkey')
data<-subset(MERGED2, JB_val_total_1y==1)
data<-na.omit(data)
# print("Sample Size=")
# print(nrow(data))


#########################Scale Continuous Variables#############################
#Structure MRI
# grep('lh_bankssts_area._.1', colnames(data))
# grep('CerebralWhiteMatterVol._.18', colnames(data))
data[, c(61:459)]<-scale(data.frame(data[, c(61:459)]))

#MID task fMRI
# grep('tfmri_ma_arvn_b_cds_clatcgelh', colnames(data))
# grep('tfmri_ma_alvsl_b_scs_vtdcrh', colnames(data))
data[, c(461:1439)]<-scale(data.frame(data[, c(461:1439)]))

#Other
contvar<-c("age_0y", "bmi_0y", "history_ratio_0y", 
       "income_0y", "high_educ_0y", "parent_age_0y", "vol", "rh_adi_perc1_0y",
       "discount_rate_1y", "totalscore_pps_1y", "totalscore_pps_2y", 
       "distress_score_pps_1y", "distress_score_pps_2y", "nihtbx_totalcomp_uncorrected_0y")

data[contvar]<-scale(data.frame(data[contvar]))


#################################Binary Treatment & Covariates######################################

data$rh_adi_bi_0y = ifelse(data$rh_adi_perc1_0y >= mean(data$rh_adi_perc1_0y), 1, 0)

# data$sex_0y<-as.factor(data$sex_0y)
# data$married_0y<-as.factor(data$married_0y)
# data$parent_identity_0y<-as.factor(data$parent_identity_0y)
# data$race_ethnicity_0y<-as.factor(data$race_ethnicity_0y)


library(fastDummies)

data<-dummy_cols(data, select_columns = c('sex_0y', 'married_0y', 'race_g', 'parent_identity_0y', 'race_ethnicity_0y'))


library(learnr)
library(DiagrammeR)
library(grf)
library(tidyverse)
library(broom)
library(fastDummies)
library(lmtest)
library(rpart)
library(glmnet)
library(splines)
library(MASS)
library(sandwich)
library(ggplot2)
library(data.table)

covariates<-c('discount_rate_1y','age_0y', 'bmi_0y', 'income_0y', 
                 'high_educ_0y', 'sex_0y_F', 'vol',
                 'married_0y_2', 'married_0y_3', 'married_0y_4', 'married_0y_5', 'married_0y_6',
                 'parent_identity_0y_2','parent_identity_0y_3', 
                 'parent_identity_0y_4', 'parent_identity_0y_5',
                 'race_ethnicity_0y_2', 'race_ethnicity_0y_3', 
                 'race_ethnicity_0y_4', 'race_ethnicity_0y_5',
                 'parent_age_0y', 
                 'cpeur2', 'eaeur1', 'iqeur2',
                 'nihtbx_totalcomp_uncorrected_0y', 'history_ratio_0y',
                'lh_rostralanteriorcingulate_area._.1', 'lh_WhiteSurfArea_area._.1', 'rh_isthmuscingulate_area._.2',
              'rh_parahippocampal_area._.2', 'rh_parsopercularis_area._.2', 'rh_temporalpole_area._.2', 
              'rh_fusiform_volume._.8', 'rh_parahippocampal_volume._.8', 'rh_parsopercularis_volume._.8', 
              'Right.Caudate._.9', 'TotalGrayVol._.9', 'wm.rh.temporalpole._.18',
              'tfmri_ma_arvn_b_cds_smglh', 'tfmri_ma_arvn_b_cds_pocgerh', 'tfmri_ma_acvn_b_cds_pcelh', 
              'tfmri_ma_acvn_b_cds_prgisrh', 'tfmri_ma_acvn_b_cds_pocgerh', 'tfmri_ma_alrvn_b_cds_postcrh', 
              'tfmri_ma_alrvn_b_cds_romdfrrh', 'tfmri_ma_asrvn_b_cds_smglh', 'tfmri_ma_asrvn_b_cds_smgrh', 
              'tfmri_ma_allvn_b_cds_tvtplh', 'tfmri_ma_allvn_b_cds_ffrh', 'tfmri_ma_asvn_b_cds_smgrh', 
              'tfmri_ma_acmvn_b_scs_cbwmrh')

W = data$rh_adi_bi_0y
X = data[, covariates]
Z = data$section8_0y
n = nrow(data)


  
################## RATE: Distress Score PLE 1year #######################
Y <- data[, 'distress_score_pps_1y']

train <- sample(1:n, n/2)

set.seed(123, kind = "Mersenne-Twister", normal.kind = "Inversion", sample.kind = "Rejection")
cf.priority <- instrumental_forest(
  X[train, ], Y[train], W[train], Z[train],
  num.trees = 50000, 
  tune.parameters = 'all',
  tune.num.trees = 5000,
  tune.num.reps = 250,
  tune.num.draws = 2000)

set.seed(123, kind = "Mersenne-Twister", normal.kind = "Inversion", sample.kind = "Rejection")
# Estimate AUTOC on held out data.
cf.eval <- instrumental_forest(
  X[-train, ], Y[-train], W[-train], Z[-train], 
  num.trees = 50000, 
  tune.parameters = 'all',
  tune.num.trees = 5000,
  tune.num.reps = 250,
  tune.num.draws = 2000)


set.seed(123, kind = "Mersenne-Twister", normal.kind = "Inversion", sample.kind = "Rejection")
tau.hat <- predict(cf.priority, X[-train, ])$predictions
rate <- rank_average_treatment_effect(cf.eval, tau.hat, target = "AUTOC")

est<-rate$estimate
se<-rate$std.err
tstat <- est / se
pvalue <- 2*(1-pnorm(abs(tstat)))
lowci<- est + -1 * qnorm(0.975) * se 
highci<- est + 1 * qnorm(0.975) * se 
rate.res<-cbind(est, se, tstat, pvalue, lowci, highci)
row.names(rate.res)<-'RATE: Distress PLEs 1y'
print(rate.res)



plot(rate, xlab = "Treated fraction", main = "TOC of Distress PLEs (1year) evaluated on ATE estimated from 50% Sample Size")  
  
  
```






```{r RATE Brain: Total 2year}
rm(list=ls())
dd_data<-read.csv("C:\\Users\\socra\\Desktop\\Brain discounting\\Data\\ABCD Delay discounting merged_wide_kNN imputed dataset.csv", header=TRUE)

dd<-c('subjectkey', 'sex_0y', 'married_0y', 'income_0y', 'age_0y', 'race_g', 'race_ethnicity_0y', 'high_educ_0y', 'bmi_0y',
      'history_ratio_0y', 'abcd_site_0y', 'discount_rate_1y',
      'totalscore_pps_1y', 'totalscore_pps_2y', 'distress_score_pps_1y', 'distress_score_pps_2y',
      'section8_0y', 'rh_adi_perc1_0y', 'parent_age_0y', 'parent_identity_0y', 
      'JB_val_total_1y', 'nihtbx_totalcomp_uncorrected_0y',
      'cpeur2', 'eaeur1', 'depeur4', 'mddeur6', 'depmulti', 'bmieur4', 'bmimulti', 'iqeur2', 'insomniaeur6', 'snoringeur1',
      'happieur4', 'ghappieur2', 'ghappimeaneur1', 'ghappihealth6', 'alcdep_eurauto', 'alcdep_afrauto', 'alcdep_metaauto',
      'asdauto', 'aspauto', 'bipauto', 'cannabisauto', 'crossauto', 'drinkauto', 'edauto', 'neuroticismauto', 'ocdauto',
      'risk4pcauto', 'risktolauto', 'scz_eurauto', 'scz_easauto', 'scz_metaauto', 'smokerauto', 'worryauto', 'anxietyauto',
      'ptsdeur4', 'ptsdmeta6', 'adhdeur6', 'vol')


smri_data<-read.csv("C:\\Users\\socra\\Desktop\\Brain Discounting\\Data\\mor.some.qc.desikan.csv", header=TRUE)

MID_fMRI_data<-read.csv("C:\\Users\\socra\\Desktop\\Brain Discounting\\Data\\ABCD MID task fMRI Desikan_all_baseline.csv", header=TRUE)

MID_fMRI_data<-subset(data.frame(MID_fMRI_data), select = -c(eventname, interview_date, 
                                                             interview_age, sex, visit,
                                                             imgincl_t1w_include, imgincl_t2w_include, imgincl_dmri_include,
                                                             imgincl_rsfmri_include, imgincl_mid_include, imgincl_nback_include,
                                                             imgincl_sst_include, tfmri_mid_all_b_tr, tfmri_mid_all_b_numtrs,
                                                             tfmri_mid_all_b_dof, tfmri_mid_all_b_nvols, tfmri_mid_all_b_subthreshnvols, 
                                                             tfmri_mid_all_b_meanmotion, tfmri_mid_all_b_maxmotion, 
                                                             tfmri_mid_all_b_meantrans, tfmri_mid_all_b_maxtrans, tfmri_mid_all_b_meanrot,
                                                             tfmri_mid_all_b_maxrot))

dd_s<-dd_data[,dd]
MERGED1<-merge(dd_s, smri_data, by='subjectkey')
MERGED2<-merge(MERGED1, MID_fMRI_data, by='subjectkey')
data<-subset(MERGED2, JB_val_total_1y==1)
data<-na.omit(data)
# print("Sample Size=")
# print(nrow(data))


#########################Scale Continuous Variables#############################
#Structure MRI
# grep('lh_bankssts_area._.1', colnames(data))
# grep('CerebralWhiteMatterVol._.18', colnames(data))
data[, c(61:459)]<-scale(data.frame(data[, c(61:459)]))

#MID task fMRI
# grep('tfmri_ma_arvn_b_cds_clatcgelh', colnames(data))
# grep('tfmri_ma_alvsl_b_scs_vtdcrh', colnames(data))
data[, c(461:1439)]<-scale(data.frame(data[, c(461:1439)]))

#Other
contvar<-c("age_0y", "bmi_0y", "history_ratio_0y", 
       "income_0y", "high_educ_0y", "parent_age_0y", "vol", "rh_adi_perc1_0y",
       "discount_rate_1y", "totalscore_pps_1y", "totalscore_pps_2y", 
       "distress_score_pps_1y", "distress_score_pps_2y", "nihtbx_totalcomp_uncorrected_0y")

data[contvar]<-scale(data.frame(data[contvar]))


#################################Binary Treatment & Covariates######################################

data$rh_adi_bi_0y = ifelse(data$rh_adi_perc1_0y >= mean(data$rh_adi_perc1_0y), 1, 0)

# data$sex_0y<-as.factor(data$sex_0y)
# data$married_0y<-as.factor(data$married_0y)
# data$parent_identity_0y<-as.factor(data$parent_identity_0y)
# data$race_ethnicity_0y<-as.factor(data$race_ethnicity_0y)


library(fastDummies)

data<-dummy_cols(data, select_columns = c('sex_0y', 'married_0y', 'race_g', 'parent_identity_0y', 'race_ethnicity_0y'))


library(learnr)
library(DiagrammeR)
library(grf)
library(tidyverse)
library(broom)
library(fastDummies)
library(lmtest)
library(rpart)
library(glmnet)
library(splines)
library(MASS)
library(sandwich)
library(ggplot2)
library(data.table)

covariates<-c('discount_rate_1y','age_0y', 'bmi_0y', 'income_0y', 
                 'high_educ_0y', 'sex_0y_F', 'vol',
                 'married_0y_2', 'married_0y_3', 'married_0y_4', 'married_0y_5', 'married_0y_6',
                 'parent_identity_0y_2','parent_identity_0y_3', 
                 'parent_identity_0y_4', 'parent_identity_0y_5',
                 'race_ethnicity_0y_2', 'race_ethnicity_0y_3', 
                 'race_ethnicity_0y_4', 'race_ethnicity_0y_5',
                 'parent_age_0y', 
                 'cpeur2', 'eaeur1', 'iqeur2',
                 'nihtbx_totalcomp_uncorrected_0y', 'history_ratio_0y',
                'lh_rostralanteriorcingulate_area._.1', 'lh_WhiteSurfArea_area._.1', 'rh_isthmuscingulate_area._.2',
              'rh_parahippocampal_area._.2', 'rh_parsopercularis_area._.2', 'rh_temporalpole_area._.2', 
              'rh_fusiform_volume._.8', 'rh_parahippocampal_volume._.8', 'rh_parsopercularis_volume._.8', 
              'Right.Caudate._.9', 'TotalGrayVol._.9', 'wm.rh.temporalpole._.18',
              'tfmri_ma_arvn_b_cds_smglh', 'tfmri_ma_arvn_b_cds_pocgerh', 'tfmri_ma_acvn_b_cds_pcelh', 
              'tfmri_ma_acvn_b_cds_prgisrh', 'tfmri_ma_acvn_b_cds_pocgerh', 'tfmri_ma_alrvn_b_cds_postcrh', 
              'tfmri_ma_alrvn_b_cds_romdfrrh', 'tfmri_ma_asrvn_b_cds_smglh', 'tfmri_ma_asrvn_b_cds_smgrh', 
              'tfmri_ma_allvn_b_cds_tvtplh', 'tfmri_ma_allvn_b_cds_ffrh', 'tfmri_ma_asvn_b_cds_smgrh', 
              'tfmri_ma_acmvn_b_scs_cbwmrh')

W = data$rh_adi_bi_0y
X = data[, covariates]
Z = data$section8_0y
n = nrow(data)


  
################## RATE: Total Score PLE 2year #######################

Y <- data[, 'totalscore_pps_2y']

train <- sample(1:n, n/2)

set.seed(123, kind = "Mersenne-Twister", normal.kind = "Inversion", sample.kind = "Rejection")
cf.priority <- instrumental_forest(
    X[train, ], Y[train], W[train], Z[train],
    num.trees = 40000, 
    tune.parameters = 'all',
    tune.num.trees = 5000,
    tune.num.reps = 250,
    tune.num.draws = 4000)

set.seed(123, kind = "Mersenne-Twister", normal.kind = "Inversion", sample.kind = "Rejection")
# Estimate AUTOC on held out data.
cf.eval <- instrumental_forest(
  X[-train, ], Y[-train], W[-train], Z[-train], 
  num.trees = 40000, 
  tune.parameters = 'all',
  tune.num.trees = 5000,
  tune.num.reps = 250,
  tune.num.draws = 4000)


set.seed(123, kind = "Mersenne-Twister", normal.kind = "Inversion", sample.kind = "Rejection")
tau.hat <- predict(cf.priority, X[-train, ])$predictions
rate <- rank_average_treatment_effect(cf.eval, tau.hat, target = "AUTOC")


est<-rate$estimate
se<-rate$std.err
tstat <- est / se
pvalue <- 2*(1-pnorm(abs(tstat)))
lowci<- est + -1 * qnorm(0.975) * se 
highci<- est + 1 * qnorm(0.975) * se 
rate.res<-cbind(est, se, tstat, pvalue, lowci, highci)
row.names(rate.res)<-'RATE: Total Score PLE 2year'
print(rate.res)


# pdf(file="totalscore_1y_RATE_brain.pdf", width=8, height=6)
plot(rate, xlab = "Treated fraction", main = "TOC of Total PLEs (2year) evaluated on ATE estimated from 50% Sample Size")  
# dev.off()
  
```




```{r RATE Brain: Distress 2year}
rm(list=ls())
dd_data<-read.csv("C:\\Users\\socra\\Desktop\\Brain discounting\\Data\\ABCD Delay discounting merged_wide_kNN imputed dataset.csv", header=TRUE)

dd<-c('subjectkey', 'sex_0y', 'married_0y', 'income_0y', 'age_0y', 'race_g', 'race_ethnicity_0y', 'high_educ_0y', 'bmi_0y',
      'history_ratio_0y', 'abcd_site_0y', 'discount_rate_1y',
      'totalscore_pps_1y', 'totalscore_pps_2y', 'distress_score_pps_1y', 'distress_score_pps_2y',
      'section8_0y', 'rh_adi_perc1_0y', 'parent_age_0y', 'parent_identity_0y', 
      'JB_val_total_1y', 'nihtbx_totalcomp_uncorrected_0y',
      'cpeur2', 'eaeur1', 'depeur4', 'mddeur6', 'depmulti', 'bmieur4', 'bmimulti', 'iqeur2', 'insomniaeur6', 'snoringeur1',
      'happieur4', 'ghappieur2', 'ghappimeaneur1', 'ghappihealth6', 'alcdep_eurauto', 'alcdep_afrauto', 'alcdep_metaauto',
      'asdauto', 'aspauto', 'bipauto', 'cannabisauto', 'crossauto', 'drinkauto', 'edauto', 'neuroticismauto', 'ocdauto',
      'risk4pcauto', 'risktolauto', 'scz_eurauto', 'scz_easauto', 'scz_metaauto', 'smokerauto', 'worryauto', 'anxietyauto',
      'ptsdeur4', 'ptsdmeta6', 'adhdeur6', 'vol')


smri_data<-read.csv("C:\\Users\\socra\\Desktop\\Brain Discounting\\Data\\mor.some.qc.desikan.csv", header=TRUE)

MID_fMRI_data<-read.csv("C:\\Users\\socra\\Desktop\\Brain Discounting\\Data\\ABCD MID task fMRI Desikan_all_baseline.csv", header=TRUE)

MID_fMRI_data<-subset(data.frame(MID_fMRI_data), select = -c(eventname, interview_date, 
                                                             interview_age, sex, visit,
                                                             imgincl_t1w_include, imgincl_t2w_include, imgincl_dmri_include,
                                                             imgincl_rsfmri_include, imgincl_mid_include, imgincl_nback_include,
                                                             imgincl_sst_include, tfmri_mid_all_b_tr, tfmri_mid_all_b_numtrs,
                                                             tfmri_mid_all_b_dof, tfmri_mid_all_b_nvols, tfmri_mid_all_b_subthreshnvols, 
                                                             tfmri_mid_all_b_meanmotion, tfmri_mid_all_b_maxmotion, 
                                                             tfmri_mid_all_b_meantrans, tfmri_mid_all_b_maxtrans, tfmri_mid_all_b_meanrot,
                                                             tfmri_mid_all_b_maxrot))

dd_s<-dd_data[,dd]
MERGED1<-merge(dd_s, smri_data, by='subjectkey')
MERGED2<-merge(MERGED1, MID_fMRI_data, by='subjectkey')
data<-subset(MERGED2, JB_val_total_1y==1)
data<-na.omit(data)
# print("Sample Size=")
# print(nrow(data))


#########################Scale Continuous Variables#############################
#Structure MRI
# grep('lh_bankssts_area._.1', colnames(data))
# grep('CerebralWhiteMatterVol._.18', colnames(data))
data[, c(61:459)]<-scale(data.frame(data[, c(61:459)]))

#MID task fMRI
# grep('tfmri_ma_arvn_b_cds_clatcgelh', colnames(data))
# grep('tfmri_ma_alvsl_b_scs_vtdcrh', colnames(data))
data[, c(461:1439)]<-scale(data.frame(data[, c(461:1439)]))

#Other
contvar<-c("age_0y", "bmi_0y", "history_ratio_0y", 
       "income_0y", "high_educ_0y", "parent_age_0y", "vol", "rh_adi_perc1_0y",
       "discount_rate_1y", "totalscore_pps_1y", "totalscore_pps_2y", 
       "distress_score_pps_1y", "distress_score_pps_2y", "nihtbx_totalcomp_uncorrected_0y")

data[contvar]<-scale(data.frame(data[contvar]))


#################################Binary Treatment & Covariates######################################

data$rh_adi_bi_0y = ifelse(data$rh_adi_perc1_0y >= mean(data$rh_adi_perc1_0y), 1, 0)

# data$sex_0y<-as.factor(data$sex_0y)
# data$married_0y<-as.factor(data$married_0y)
# data$parent_identity_0y<-as.factor(data$parent_identity_0y)
# data$race_ethnicity_0y<-as.factor(data$race_ethnicity_0y)


library(fastDummies)

data<-dummy_cols(data, select_columns = c('sex_0y', 'married_0y', 'race_g', 'parent_identity_0y', 'race_ethnicity_0y'))


library(learnr)
library(DiagrammeR)
library(grf)
library(tidyverse)
library(broom)
library(fastDummies)
library(lmtest)
library(rpart)
library(glmnet)
library(splines)
library(MASS)
library(sandwich)
library(ggplot2)
library(data.table)

covariates<-c('discount_rate_1y','age_0y', 'bmi_0y', 'income_0y', 
                 'high_educ_0y', 'sex_0y_F', 'vol',
                 'married_0y_2', 'married_0y_3', 'married_0y_4', 'married_0y_5', 'married_0y_6',
                 'parent_identity_0y_2','parent_identity_0y_3', 
                 'parent_identity_0y_4', 'parent_identity_0y_5',
                 'race_ethnicity_0y_2', 'race_ethnicity_0y_3', 
                 'race_ethnicity_0y_4', 'race_ethnicity_0y_5',
                 'parent_age_0y', 
                 'cpeur2', 'eaeur1', 'iqeur2',
                 'nihtbx_totalcomp_uncorrected_0y', 'history_ratio_0y',
                'lh_rostralanteriorcingulate_area._.1', 'lh_WhiteSurfArea_area._.1', 'rh_isthmuscingulate_area._.2',
              'rh_parahippocampal_area._.2', 'rh_parsopercularis_area._.2', 'rh_temporalpole_area._.2', 
              'rh_fusiform_volume._.8', 'rh_parahippocampal_volume._.8', 'rh_parsopercularis_volume._.8', 
              'Right.Caudate._.9', 'TotalGrayVol._.9', 'wm.rh.temporalpole._.18',
              'tfmri_ma_arvn_b_cds_smglh', 'tfmri_ma_arvn_b_cds_pocgerh', 'tfmri_ma_acvn_b_cds_pcelh', 
              'tfmri_ma_acvn_b_cds_prgisrh', 'tfmri_ma_acvn_b_cds_pocgerh', 'tfmri_ma_alrvn_b_cds_postcrh', 
              'tfmri_ma_alrvn_b_cds_romdfrrh', 'tfmri_ma_asrvn_b_cds_smglh', 'tfmri_ma_asrvn_b_cds_smgrh', 
              'tfmri_ma_allvn_b_cds_tvtplh', 'tfmri_ma_allvn_b_cds_ffrh', 'tfmri_ma_asvn_b_cds_smgrh', 
              'tfmri_ma_acmvn_b_scs_cbwmrh')

W = data$rh_adi_bi_0y
X = data[, covariates]
Z = data$section8_0y
n = nrow(data)


  
################## RATE: Distress Score PLE 2year #######################
Y <- data[, 'distress_score_pps_2y']

train <- sample(1:n, n/2)

set.seed(123, kind = "Mersenne-Twister", normal.kind = "Inversion", sample.kind = "Rejection")
cf.priority <- instrumental_forest(
  X[train, ], Y[train], W[train], Z[train],
  num.trees = 50000, 
  tune.parameters = 'all',
  tune.num.trees = 5000,
  tune.num.reps = 250,
  tune.num.draws = 2000)

set.seed(123, kind = "Mersenne-Twister", normal.kind = "Inversion", sample.kind = "Rejection")
# Estimate AUTOC on held out data.
cf.eval <- instrumental_forest(
  X[-train, ], Y[-train], W[-train], Z[-train], 
  num.trees = 50000, 
  tune.parameters = 'all',
  tune.num.trees = 5000,
  tune.num.reps = 250,
  tune.num.draws = 2000)


set.seed(123, kind = "Mersenne-Twister", normal.kind = "Inversion", sample.kind = "Rejection")
tau.hat <- predict(cf.priority, X[-train, ])$predictions
rate <- rank_average_treatment_effect(cf.eval, tau.hat, target = "AUTOC")

est<-rate$estimate
se<-rate$std.err
tstat <- est / se
pvalue <- 2*(1-pnorm(abs(tstat)))
lowci<- est + -1 * qnorm(0.975) * se 
highci<- est + 1 * qnorm(0.975) * se 
rate.res<-cbind(est, se, tstat, pvalue, lowci, highci)
row.names(rate.res)<-'RATE: Distress PLEs 2y'
print(rate.res)



plot(rate, xlab = "Treated fraction", main = "TOC of Distress PLEs (2year) evaluated on ATE estimated from 50% Sample Size")  
  
  
```




```{r RATE Brain: Distress DI 1year}
rm(list=ls())
dd_data<-read.csv("C:\\Users\\socra\\Desktop\\Brain discounting\\Data\\ABCD Delay discounting merged_wide_kNN imputed dataset.csv", header=TRUE)

dd<-c('subjectkey', 'sex_0y', 'married_0y', 'income_0y', 'age_0y', 'race_g', 'race_ethnicity_0y', 'high_educ_0y', 'bmi_0y',
      'history_ratio_0y', 'abcd_site_0y', 'discount_rate_1y',
      'totalscore_pps_1y', 'totalscore_pps_2y', 'distress_score_pps_1y', 'distress_score_pps_2y',
      'section8_0y', 'rh_adi_perc1_0y', 'parent_age_0y', 'parent_identity_0y', 
      'JB_val_total_1y', 'nihtbx_totalcomp_uncorrected_0y',
      'cpeur2', 'eaeur1', 'depeur4', 'mddeur6', 'depmulti', 'bmieur4', 'bmimulti', 'iqeur2', 'insomniaeur6', 'snoringeur1',
      'happieur4', 'ghappieur2', 'ghappimeaneur1', 'ghappihealth6', 'alcdep_eurauto', 'alcdep_afrauto', 'alcdep_metaauto',
      'asdauto', 'aspauto', 'bipauto', 'cannabisauto', 'crossauto', 'drinkauto', 'edauto', 'neuroticismauto', 'ocdauto',
      'risk4pcauto', 'risktolauto', 'scz_eurauto', 'scz_easauto', 'scz_metaauto', 'smokerauto', 'worryauto', 'anxietyauto',
      'ptsdeur4', 'ptsdmeta6', 'adhdeur6', 'vol',
      'distress_score_di_1y', 'distress_score_pd_1y', 
      'distress_score_di_2y', 'distress_score_pd_2y')


smri_data<-read.csv("C:\\Users\\socra\\Desktop\\Brain Discounting\\Data\\mor.some.qc.desikan.csv", header=TRUE)

MID_fMRI_data<-read.csv("C:\\Users\\socra\\Desktop\\Brain Discounting\\Data\\ABCD MID task fMRI Desikan_all_baseline.csv", header=TRUE)

MID_fMRI_data<-subset(data.frame(MID_fMRI_data), select = -c(eventname, interview_date, 
                                                             interview_age, sex, visit,
                                                             imgincl_t1w_include, imgincl_t2w_include, imgincl_dmri_include,
                                                             imgincl_rsfmri_include, imgincl_mid_include, imgincl_nback_include,
                                                             imgincl_sst_include, tfmri_mid_all_b_tr, tfmri_mid_all_b_numtrs,
                                                             tfmri_mid_all_b_dof, tfmri_mid_all_b_nvols, tfmri_mid_all_b_subthreshnvols, 
                                                             tfmri_mid_all_b_meanmotion, tfmri_mid_all_b_maxmotion, 
                                                             tfmri_mid_all_b_meantrans, tfmri_mid_all_b_maxtrans, tfmri_mid_all_b_meanrot,
                                                             tfmri_mid_all_b_maxrot))

dd_s<-dd_data[,dd]
MERGED1<-merge(dd_s, smri_data, by='subjectkey')
MERGED2<-merge(MERGED1, MID_fMRI_data, by='subjectkey')
data<-subset(MERGED2, JB_val_total_1y==1)
data<-na.omit(data)
# print("Sample Size=")
# print(nrow(data))


#########################Scale Continuous Variables#############################
#Structure MRI
# grep('lh_bankssts_area._.1', colnames(data))
# grep('CerebralWhiteMatterVol._.18', colnames(data))
data[, c(61:459)]<-scale(data.frame(data[, c(61:459)]))

#MID task fMRI
# grep('tfmri_ma_arvn_b_cds_clatcgelh', colnames(data))
# grep('tfmri_ma_alvsl_b_scs_vtdcrh', colnames(data))
data[, c(461:1439)]<-scale(data.frame(data[, c(461:1439)]))

#Other
contvar<-c("age_0y", "bmi_0y", "history_ratio_0y", 
       "income_0y", "high_educ_0y", "parent_age_0y", "vol", "rh_adi_perc1_0y",
       "discount_rate_1y", "totalscore_pps_1y", "totalscore_pps_2y", 
       "distress_score_pps_1y", "distress_score_pps_2y", "nihtbx_totalcomp_uncorrected_0y",
       'distress_score_di_1y', 'distress_score_pd_1y', 
       'distress_score_di_2y', 'distress_score_pd_2y')

data[contvar]<-scale(data.frame(data[contvar]))


#################################Binary Treatment & Covariates######################################

data$rh_adi_bi_0y = ifelse(data$rh_adi_perc1_0y >= mean(data$rh_adi_perc1_0y), 1, 0)

# data$sex_0y<-as.factor(data$sex_0y)
# data$married_0y<-as.factor(data$married_0y)
# data$parent_identity_0y<-as.factor(data$parent_identity_0y)
# data$race_ethnicity_0y<-as.factor(data$race_ethnicity_0y)


library(fastDummies)

data<-dummy_cols(data, select_columns = c('sex_0y', 'married_0y', 'race_g', 'parent_identity_0y', 'race_ethnicity_0y'))


library(learnr)
library(DiagrammeR)
library(grf)
library(tidyverse)
library(broom)
library(fastDummies)
library(lmtest)
library(rpart)
library(glmnet)
library(splines)
library(MASS)
library(sandwich)
library(ggplot2)
library(data.table)

covariates<-c('discount_rate_1y','age_0y', 'bmi_0y', 'income_0y', 
                 'high_educ_0y', 'sex_0y_F', 'vol',
                 'married_0y_2', 'married_0y_3', 'married_0y_4', 'married_0y_5', 'married_0y_6',
                 'parent_identity_0y_2','parent_identity_0y_3', 
                 'parent_identity_0y_4', 'parent_identity_0y_5',
                 'race_ethnicity_0y_2', 'race_ethnicity_0y_3', 
                 'race_ethnicity_0y_4', 'race_ethnicity_0y_5',
                 'parent_age_0y', 
                 'cpeur2', 'eaeur1', 'iqeur2',
                 'nihtbx_totalcomp_uncorrected_0y', 'history_ratio_0y',
                'lh_rostralanteriorcingulate_area._.1', 'lh_WhiteSurfArea_area._.1', 'rh_isthmuscingulate_area._.2',
              'rh_parahippocampal_area._.2', 'rh_parsopercularis_area._.2', 'rh_temporalpole_area._.2', 
              'rh_fusiform_volume._.8', 'rh_parahippocampal_volume._.8', 'rh_parsopercularis_volume._.8', 
              'Right.Caudate._.9', 'TotalGrayVol._.9', 'wm.rh.temporalpole._.18',
              'tfmri_ma_arvn_b_cds_smglh', 'tfmri_ma_arvn_b_cds_pocgerh', 'tfmri_ma_acvn_b_cds_pcelh', 
              'tfmri_ma_acvn_b_cds_prgisrh', 'tfmri_ma_acvn_b_cds_pocgerh', 'tfmri_ma_alrvn_b_cds_postcrh', 
              'tfmri_ma_alrvn_b_cds_romdfrrh', 'tfmri_ma_asrvn_b_cds_smglh', 'tfmri_ma_asrvn_b_cds_smgrh', 
              'tfmri_ma_allvn_b_cds_tvtplh', 'tfmri_ma_allvn_b_cds_ffrh', 'tfmri_ma_asvn_b_cds_smgrh', 
              'tfmri_ma_acmvn_b_scs_cbwmrh')

W = data$rh_adi_bi_0y
X = data[, covariates]
Z = data$section8_0y
n = nrow(data)


  
################## RATE: Distress Score DI 1year #######################
Y <- data[, 'distress_score_di_1y']

train <- sample(1:n, n/2)

set.seed(123, kind = "Mersenne-Twister", normal.kind = "Inversion", sample.kind = "Rejection")
cf.priority <- instrumental_forest(
  X[train, ], Y[train], W[train], Z[train],
  num.trees = 50000, 
  tune.parameters = 'all',
  tune.num.trees = 5000,
  tune.num.reps = 250,
  tune.num.draws = 2000)

set.seed(123, kind = "Mersenne-Twister", normal.kind = "Inversion", sample.kind = "Rejection")
# Estimate AUTOC on held out data.
cf.eval <- instrumental_forest(
  X[-train, ], Y[-train], W[-train], Z[-train], 
  num.trees = 50000, 
  tune.parameters = 'all',
  tune.num.trees = 5000,
  tune.num.reps = 250,
  tune.num.draws = 2000)


set.seed(123, kind = "Mersenne-Twister", normal.kind = "Inversion", sample.kind = "Rejection")
tau.hat <- predict(cf.priority, X[-train, ])$predictions
rate <- rank_average_treatment_effect(cf.eval, tau.hat, target = "AUTOC")

est<-rate$estimate
se<-rate$std.err
tstat <- est / se
pvalue <- 2*(1-pnorm(abs(tstat)))
lowci<- est + -1 * qnorm(0.975) * se 
highci<- est + 1 * qnorm(0.975) * se 
rate.res<-cbind(est, se, tstat, pvalue, lowci, highci)
row.names(rate.res)<-'RATE: Distress DI 1y'
print(rate.res)



plot(rate, xlab = "Treated fraction", main = "TOC of Delusion-Like Experiences (1year) evaluated on ATE estimated from 50% Sample Size")  
  
  
```




```{r RATE Brain: Distress PD 1year}
rm(list=ls())
dd_data<-read.csv("C:\\Users\\socra\\Desktop\\Brain discounting\\Data\\ABCD Delay discounting merged_wide_kNN imputed dataset.csv", header=TRUE)

dd<-c('subjectkey', 'sex_0y', 'married_0y', 'income_0y', 'age_0y', 'race_g', 'race_ethnicity_0y', 'high_educ_0y', 'bmi_0y',
      'history_ratio_0y', 'abcd_site_0y', 'discount_rate_1y',
      'totalscore_pps_1y', 'totalscore_pps_2y', 'distress_score_pps_1y', 'distress_score_pps_2y',
      'section8_0y', 'rh_adi_perc1_0y', 'parent_age_0y', 'parent_identity_0y', 
      'JB_val_total_1y', 'nihtbx_totalcomp_uncorrected_0y',
      'cpeur2', 'eaeur1', 'depeur4', 'mddeur6', 'depmulti', 'bmieur4', 'bmimulti', 'iqeur2', 'insomniaeur6', 'snoringeur1',
      'happieur4', 'ghappieur2', 'ghappimeaneur1', 'ghappihealth6', 'alcdep_eurauto', 'alcdep_afrauto', 'alcdep_metaauto',
      'asdauto', 'aspauto', 'bipauto', 'cannabisauto', 'crossauto', 'drinkauto', 'edauto', 'neuroticismauto', 'ocdauto',
      'risk4pcauto', 'risktolauto', 'scz_eurauto', 'scz_easauto', 'scz_metaauto', 'smokerauto', 'worryauto', 'anxietyauto',
      'ptsdeur4', 'ptsdmeta6', 'adhdeur6', 'vol',
      'distress_score_di_1y', 'distress_score_pd_1y', 
      'distress_score_di_2y', 'distress_score_pd_2y')


smri_data<-read.csv("C:\\Users\\socra\\Desktop\\Brain Discounting\\Data\\mor.some.qc.desikan.csv", header=TRUE)

MID_fMRI_data<-read.csv("C:\\Users\\socra\\Desktop\\Brain Discounting\\Data\\ABCD MID task fMRI Desikan_all_baseline.csv", header=TRUE)

MID_fMRI_data<-subset(data.frame(MID_fMRI_data), select = -c(eventname, interview_date, 
                                                             interview_age, sex, visit,
                                                             imgincl_t1w_include, imgincl_t2w_include, imgincl_dmri_include,
                                                             imgincl_rsfmri_include, imgincl_mid_include, imgincl_nback_include,
                                                             imgincl_sst_include, tfmri_mid_all_b_tr, tfmri_mid_all_b_numtrs,
                                                             tfmri_mid_all_b_dof, tfmri_mid_all_b_nvols, tfmri_mid_all_b_subthreshnvols, 
                                                             tfmri_mid_all_b_meanmotion, tfmri_mid_all_b_maxmotion, 
                                                             tfmri_mid_all_b_meantrans, tfmri_mid_all_b_maxtrans, tfmri_mid_all_b_meanrot,
                                                             tfmri_mid_all_b_maxrot))

dd_s<-dd_data[,dd]
MERGED1<-merge(dd_s, smri_data, by='subjectkey')
MERGED2<-merge(MERGED1, MID_fMRI_data, by='subjectkey')
data<-subset(MERGED2, JB_val_total_1y==1)
data<-na.omit(data)
# print("Sample Size=")
# print(nrow(data))


#########################Scale Continuous Variables#############################
#Structure MRI
# grep('lh_bankssts_area._.1', colnames(data))
# grep('CerebralWhiteMatterVol._.18', colnames(data))
data[, c(61:459)]<-scale(data.frame(data[, c(61:459)]))

#MID task fMRI
# grep('tfmri_ma_arvn_b_cds_clatcgelh', colnames(data))
# grep('tfmri_ma_alvsl_b_scs_vtdcrh', colnames(data))
data[, c(461:1439)]<-scale(data.frame(data[, c(461:1439)]))

#Other
contvar<-c("age_0y", "bmi_0y", "history_ratio_0y", 
       "income_0y", "high_educ_0y", "parent_age_0y", "vol", "rh_adi_perc1_0y",
       "discount_rate_1y", "totalscore_pps_1y", "totalscore_pps_2y", 
       "distress_score_pps_1y", "distress_score_pps_2y", "nihtbx_totalcomp_uncorrected_0y",
       'distress_score_di_1y', 'distress_score_pd_1y', 
       'distress_score_di_2y', 'distress_score_pd_2y')

data[contvar]<-scale(data.frame(data[contvar]))


#################################Binary Treatment & Covariates######################################

data$rh_adi_bi_0y = ifelse(data$rh_adi_perc1_0y >= mean(data$rh_adi_perc1_0y), 1, 0)

# data$sex_0y<-as.factor(data$sex_0y)
# data$married_0y<-as.factor(data$married_0y)
# data$parent_identity_0y<-as.factor(data$parent_identity_0y)
# data$race_ethnicity_0y<-as.factor(data$race_ethnicity_0y)


library(fastDummies)

data<-dummy_cols(data, select_columns = c('sex_0y', 'married_0y', 'race_g', 'parent_identity_0y', 'race_ethnicity_0y'))


library(learnr)
library(DiagrammeR)
library(grf)
library(tidyverse)
library(broom)
library(fastDummies)
library(lmtest)
library(rpart)
library(glmnet)
library(splines)
library(MASS)
library(sandwich)
library(ggplot2)
library(data.table)

covariates<-c('discount_rate_1y','age_0y', 'bmi_0y', 'income_0y', 
                 'high_educ_0y', 'sex_0y_F', 'vol',
                 'married_0y_2', 'married_0y_3', 'married_0y_4', 'married_0y_5', 'married_0y_6',
                 'parent_identity_0y_2','parent_identity_0y_3', 
                 'parent_identity_0y_4', 'parent_identity_0y_5',
                 'race_ethnicity_0y_2', 'race_ethnicity_0y_3', 
                 'race_ethnicity_0y_4', 'race_ethnicity_0y_5',
                 'parent_age_0y', 
                 'cpeur2', 'eaeur1', 'iqeur2',
                 'nihtbx_totalcomp_uncorrected_0y', 'history_ratio_0y',
                'lh_rostralanteriorcingulate_area._.1', 'lh_WhiteSurfArea_area._.1', 'rh_isthmuscingulate_area._.2',
              'rh_parahippocampal_area._.2', 'rh_parsopercularis_area._.2', 'rh_temporalpole_area._.2', 
              'rh_fusiform_volume._.8', 'rh_parahippocampal_volume._.8', 'rh_parsopercularis_volume._.8', 
              'Right.Caudate._.9', 'TotalGrayVol._.9', 'wm.rh.temporalpole._.18',
              'tfmri_ma_arvn_b_cds_smglh', 'tfmri_ma_arvn_b_cds_pocgerh', 'tfmri_ma_acvn_b_cds_pcelh', 
              'tfmri_ma_acvn_b_cds_prgisrh', 'tfmri_ma_acvn_b_cds_pocgerh', 'tfmri_ma_alrvn_b_cds_postcrh', 
              'tfmri_ma_alrvn_b_cds_romdfrrh', 'tfmri_ma_asrvn_b_cds_smglh', 'tfmri_ma_asrvn_b_cds_smgrh', 
              'tfmri_ma_allvn_b_cds_tvtplh', 'tfmri_ma_allvn_b_cds_ffrh', 'tfmri_ma_asvn_b_cds_smgrh', 
              'tfmri_ma_acmvn_b_scs_cbwmrh')

W = data$rh_adi_bi_0y
X = data[, covariates]
Z = data$section8_0y
n = nrow(data)


  
################## RATE: Distress Score PD 1year #######################
Y <- data[, 'distress_score_pd_1y']

train <- sample(1:n, n/2)

set.seed(123, kind = "Mersenne-Twister", normal.kind = "Inversion", sample.kind = "Rejection")
cf.priority <- instrumental_forest(
  X[train, ], Y[train], W[train], Z[train],
  num.trees = 50000, 
  tune.parameters = 'all',
  tune.num.trees = 5000,
  tune.num.reps = 250,
  tune.num.draws = 2000)

set.seed(123, kind = "Mersenne-Twister", normal.kind = "Inversion", sample.kind = "Rejection")
# Estimate AUTOC on held out data.
cf.eval <- instrumental_forest(
  X[-train, ], Y[-train], W[-train], Z[-train], 
  num.trees = 50000, 
  tune.parameters = 'all',
  tune.num.trees = 5000,
  tune.num.reps = 250,
  tune.num.draws = 2000)


set.seed(123, kind = "Mersenne-Twister", normal.kind = "Inversion", sample.kind = "Rejection")
tau.hat <- predict(cf.priority, X[-train, ])$predictions
rate <- rank_average_treatment_effect(cf.eval, tau.hat, target = "AUTOC")

est<-rate$estimate
se<-rate$std.err
tstat <- est / se
pvalue <- 2*(1-pnorm(abs(tstat)))
lowci<- est + -1 * qnorm(0.975) * se 
highci<- est + 1 * qnorm(0.975) * se 
rate.res<-cbind(est, se, tstat, pvalue, lowci, highci)
row.names(rate.res)<-'RATE: Distress PD 1y'
print(rate.res)



plot(rate, xlab = "Treated fraction", main = "TOC of Hallucination-Like Experiences (1year) evaluated on ATE estimated from 50% Sample Size")  
  
  
```




```{r RATE Brain: Distress DI 2year}
rm(list=ls())
dd_data<-read.csv("C:\\Users\\socra\\Desktop\\Brain discounting\\Data\\ABCD Delay discounting merged_wide_kNN imputed dataset.csv", header=TRUE)

dd<-c('subjectkey', 'sex_0y', 'married_0y', 'income_0y', 'age_0y', 'race_g', 'race_ethnicity_0y', 'high_educ_0y', 'bmi_0y',
      'history_ratio_0y', 'abcd_site_0y', 'discount_rate_1y',
      'totalscore_pps_1y', 'totalscore_pps_2y', 'distress_score_pps_1y', 'distress_score_pps_2y',
      'section8_0y', 'rh_adi_perc1_0y', 'parent_age_0y', 'parent_identity_0y', 
      'JB_val_total_1y', 'nihtbx_totalcomp_uncorrected_0y',
      'cpeur2', 'eaeur1', 'depeur4', 'mddeur6', 'depmulti', 'bmieur4', 'bmimulti', 'iqeur2', 'insomniaeur6', 'snoringeur1',
      'happieur4', 'ghappieur2', 'ghappimeaneur1', 'ghappihealth6', 'alcdep_eurauto', 'alcdep_afrauto', 'alcdep_metaauto',
      'asdauto', 'aspauto', 'bipauto', 'cannabisauto', 'crossauto', 'drinkauto', 'edauto', 'neuroticismauto', 'ocdauto',
      'risk4pcauto', 'risktolauto', 'scz_eurauto', 'scz_easauto', 'scz_metaauto', 'smokerauto', 'worryauto', 'anxietyauto',
      'ptsdeur4', 'ptsdmeta6', 'adhdeur6', 'vol',
      'distress_score_di_1y', 'distress_score_pd_1y', 
      'distress_score_di_2y', 'distress_score_pd_2y')


smri_data<-read.csv("C:\\Users\\socra\\Desktop\\Brain Discounting\\Data\\mor.some.qc.desikan.csv", header=TRUE)

MID_fMRI_data<-read.csv("C:\\Users\\socra\\Desktop\\Brain Discounting\\Data\\ABCD MID task fMRI Desikan_all_baseline.csv", header=TRUE)

MID_fMRI_data<-subset(data.frame(MID_fMRI_data), select = -c(eventname, interview_date, 
                                                             interview_age, sex, visit,
                                                             imgincl_t1w_include, imgincl_t2w_include, imgincl_dmri_include,
                                                             imgincl_rsfmri_include, imgincl_mid_include, imgincl_nback_include,
                                                             imgincl_sst_include, tfmri_mid_all_b_tr, tfmri_mid_all_b_numtrs,
                                                             tfmri_mid_all_b_dof, tfmri_mid_all_b_nvols, tfmri_mid_all_b_subthreshnvols, 
                                                             tfmri_mid_all_b_meanmotion, tfmri_mid_all_b_maxmotion, 
                                                             tfmri_mid_all_b_meantrans, tfmri_mid_all_b_maxtrans, tfmri_mid_all_b_meanrot,
                                                             tfmri_mid_all_b_maxrot))

dd_s<-dd_data[,dd]
MERGED1<-merge(dd_s, smri_data, by='subjectkey')
MERGED2<-merge(MERGED1, MID_fMRI_data, by='subjectkey')
data<-subset(MERGED2, JB_val_total_1y==1)
data<-na.omit(data)
# print("Sample Size=")
# print(nrow(data))


#########################Scale Continuous Variables#############################
#Structure MRI
# grep('lh_bankssts_area._.1', colnames(data))
# grep('CerebralWhiteMatterVol._.18', colnames(data))
data[, c(61:459)]<-scale(data.frame(data[, c(61:459)]))

#MID task fMRI
# grep('tfmri_ma_arvn_b_cds_clatcgelh', colnames(data))
# grep('tfmri_ma_alvsl_b_scs_vtdcrh', colnames(data))
data[, c(461:1439)]<-scale(data.frame(data[, c(461:1439)]))

#Other
contvar<-c("age_0y", "bmi_0y", "history_ratio_0y", 
       "income_0y", "high_educ_0y", "parent_age_0y", "vol", "rh_adi_perc1_0y",
       "discount_rate_1y", "totalscore_pps_1y", "totalscore_pps_2y", 
       "distress_score_pps_1y", "distress_score_pps_2y", "nihtbx_totalcomp_uncorrected_0y",
       'distress_score_di_1y', 'distress_score_pd_1y', 
       'distress_score_di_2y', 'distress_score_pd_2y')

data[contvar]<-scale(data.frame(data[contvar]))


#################################Binary Treatment & Covariates######################################

data$rh_adi_bi_0y = ifelse(data$rh_adi_perc1_0y >= mean(data$rh_adi_perc1_0y), 1, 0)

# data$sex_0y<-as.factor(data$sex_0y)
# data$married_0y<-as.factor(data$married_0y)
# data$parent_identity_0y<-as.factor(data$parent_identity_0y)
# data$race_ethnicity_0y<-as.factor(data$race_ethnicity_0y)


library(fastDummies)

data<-dummy_cols(data, select_columns = c('sex_0y', 'married_0y', 'race_g', 'parent_identity_0y', 'race_ethnicity_0y'))


library(learnr)
library(DiagrammeR)
library(grf)
library(tidyverse)
library(broom)
library(fastDummies)
library(lmtest)
library(rpart)
library(glmnet)
library(splines)
library(MASS)
library(sandwich)
library(ggplot2)
library(data.table)

covariates<-c('discount_rate_1y','age_0y', 'bmi_0y', 'income_0y', 
                 'high_educ_0y', 'sex_0y_F', 'vol',
                 'married_0y_2', 'married_0y_3', 'married_0y_4', 'married_0y_5', 'married_0y_6',
                 'parent_identity_0y_2','parent_identity_0y_3', 
                 'parent_identity_0y_4', 'parent_identity_0y_5',
                 'race_ethnicity_0y_2', 'race_ethnicity_0y_3', 
                 'race_ethnicity_0y_4', 'race_ethnicity_0y_5',
                 'parent_age_0y', 
                 'cpeur2', 'eaeur1', 'iqeur2',
                 'nihtbx_totalcomp_uncorrected_0y', 'history_ratio_0y',
                'lh_rostralanteriorcingulate_area._.1', 'lh_WhiteSurfArea_area._.1', 'rh_isthmuscingulate_area._.2',
              'rh_parahippocampal_area._.2', 'rh_parsopercularis_area._.2', 'rh_temporalpole_area._.2', 
              'rh_fusiform_volume._.8', 'rh_parahippocampal_volume._.8', 'rh_parsopercularis_volume._.8', 
              'Right.Caudate._.9', 'TotalGrayVol._.9', 'wm.rh.temporalpole._.18',
              'tfmri_ma_arvn_b_cds_smglh', 'tfmri_ma_arvn_b_cds_pocgerh', 'tfmri_ma_acvn_b_cds_pcelh', 
              'tfmri_ma_acvn_b_cds_prgisrh', 'tfmri_ma_acvn_b_cds_pocgerh', 'tfmri_ma_alrvn_b_cds_postcrh', 
              'tfmri_ma_alrvn_b_cds_romdfrrh', 'tfmri_ma_asrvn_b_cds_smglh', 'tfmri_ma_asrvn_b_cds_smgrh', 
              'tfmri_ma_allvn_b_cds_tvtplh', 'tfmri_ma_allvn_b_cds_ffrh', 'tfmri_ma_asvn_b_cds_smgrh', 
              'tfmri_ma_acmvn_b_scs_cbwmrh')

W = data$rh_adi_bi_0y
X = data[, covariates]
Z = data$section8_0y
n = nrow(data)


  
################## RATE: Distress Score DI 2year #######################
Y <- data[, 'distress_score_di_2y']

train <- sample(1:n, n/2)

set.seed(123, kind = "Mersenne-Twister", normal.kind = "Inversion", sample.kind = "Rejection")
cf.priority <- instrumental_forest(
  X[train, ], Y[train], W[train], Z[train],
  num.trees = 50000, 
  tune.parameters = 'all',
  tune.num.trees = 5000,
  tune.num.reps = 250,
  tune.num.draws = 2000)

set.seed(123, kind = "Mersenne-Twister", normal.kind = "Inversion", sample.kind = "Rejection")
# Estimate AUTOC on held out data.
cf.eval <- instrumental_forest(
  X[-train, ], Y[-train], W[-train], Z[-train], 
  num.trees = 50000, 
  tune.parameters = 'all',
  tune.num.trees = 5000,
  tune.num.reps = 250,
  tune.num.draws = 2000)


set.seed(123, kind = "Mersenne-Twister", normal.kind = "Inversion", sample.kind = "Rejection")
tau.hat <- predict(cf.priority, X[-train, ])$predictions
rate <- rank_average_treatment_effect(cf.eval, tau.hat, target = "AUTOC")

est<-rate$estimate
se<-rate$std.err
tstat <- est / se
pvalue <- 2*(1-pnorm(abs(tstat)))
lowci<- est + -1 * qnorm(0.975) * se 
highci<- est + 1 * qnorm(0.975) * se 
rate.res<-cbind(est, se, tstat, pvalue, lowci, highci)
row.names(rate.res)<-'RATE: Distress DI 2y'
print(rate.res)



plot(rate, xlab = "Treated fraction", main = "TOC of Delusion-Like Experiences (2year) evaluated on ATE estimated from 50% Sample Size")  
  
  
```





```{r RATE Brain: Distress PD 2year}
rm(list=ls())
dd_data<-read.csv("C:\\Users\\socra\\Desktop\\Brain discounting\\Data\\ABCD Delay discounting merged_wide_kNN imputed dataset.csv", header=TRUE)

dd<-c('subjectkey', 'sex_0y', 'married_0y', 'income_0y', 'age_0y', 'race_g', 'race_ethnicity_0y', 'high_educ_0y', 'bmi_0y',
      'history_ratio_0y', 'abcd_site_0y', 'discount_rate_1y',
      'totalscore_pps_1y', 'totalscore_pps_2y', 'distress_score_pps_1y', 'distress_score_pps_2y',
      'section8_0y', 'rh_adi_perc1_0y', 'parent_age_0y', 'parent_identity_0y', 
      'JB_val_total_1y', 'nihtbx_totalcomp_uncorrected_0y',
      'cpeur2', 'eaeur1', 'depeur4', 'mddeur6', 'depmulti', 'bmieur4', 'bmimulti', 'iqeur2', 'insomniaeur6', 'snoringeur1',
      'happieur4', 'ghappieur2', 'ghappimeaneur1', 'ghappihealth6', 'alcdep_eurauto', 'alcdep_afrauto', 'alcdep_metaauto',
      'asdauto', 'aspauto', 'bipauto', 'cannabisauto', 'crossauto', 'drinkauto', 'edauto', 'neuroticismauto', 'ocdauto',
      'risk4pcauto', 'risktolauto', 'scz_eurauto', 'scz_easauto', 'scz_metaauto', 'smokerauto', 'worryauto', 'anxietyauto',
      'ptsdeur4', 'ptsdmeta6', 'adhdeur6', 'vol',
      'distress_score_di_1y', 'distress_score_pd_1y', 
      'distress_score_di_2y', 'distress_score_pd_2y')


smri_data<-read.csv("C:\\Users\\socra\\Desktop\\Brain Discounting\\Data\\mor.some.qc.desikan.csv", header=TRUE)

MID_fMRI_data<-read.csv("C:\\Users\\socra\\Desktop\\Brain Discounting\\Data\\ABCD MID task fMRI Desikan_all_baseline.csv", header=TRUE)

MID_fMRI_data<-subset(data.frame(MID_fMRI_data), select = -c(eventname, interview_date, 
                                                             interview_age, sex, visit,
                                                             imgincl_t1w_include, imgincl_t2w_include, imgincl_dmri_include,
                                                             imgincl_rsfmri_include, imgincl_mid_include, imgincl_nback_include,
                                                             imgincl_sst_include, tfmri_mid_all_b_tr, tfmri_mid_all_b_numtrs,
                                                             tfmri_mid_all_b_dof, tfmri_mid_all_b_nvols, tfmri_mid_all_b_subthreshnvols, 
                                                             tfmri_mid_all_b_meanmotion, tfmri_mid_all_b_maxmotion, 
                                                             tfmri_mid_all_b_meantrans, tfmri_mid_all_b_maxtrans, tfmri_mid_all_b_meanrot,
                                                             tfmri_mid_all_b_maxrot))

dd_s<-dd_data[,dd]
MERGED1<-merge(dd_s, smri_data, by='subjectkey')
MERGED2<-merge(MERGED1, MID_fMRI_data, by='subjectkey')
data<-subset(MERGED2, JB_val_total_1y==1)
data<-na.omit(data)
# print("Sample Size=")
# print(nrow(data))


#########################Scale Continuous Variables#############################
#Structure MRI
# grep('lh_bankssts_area._.1', colnames(data))
# grep('CerebralWhiteMatterVol._.18', colnames(data))
data[, c(61:459)]<-scale(data.frame(data[, c(61:459)]))

#MID task fMRI
# grep('tfmri_ma_arvn_b_cds_clatcgelh', colnames(data))
# grep('tfmri_ma_alvsl_b_scs_vtdcrh', colnames(data))
data[, c(461:1439)]<-scale(data.frame(data[, c(461:1439)]))

#Other
contvar<-c("age_0y", "bmi_0y", "history_ratio_0y", 
       "income_0y", "high_educ_0y", "parent_age_0y", "vol", "rh_adi_perc1_0y",
       "discount_rate_1y", "totalscore_pps_1y", "totalscore_pps_2y", 
       "distress_score_pps_1y", "distress_score_pps_2y", "nihtbx_totalcomp_uncorrected_0y",
       'distress_score_di_1y', 'distress_score_pd_1y', 
       'distress_score_di_2y', 'distress_score_pd_2y')

data[contvar]<-scale(data.frame(data[contvar]))


#################################Binary Treatment & Covariates######################################

data$rh_adi_bi_0y = ifelse(data$rh_adi_perc1_0y >= mean(data$rh_adi_perc1_0y), 1, 0)

# data$sex_0y<-as.factor(data$sex_0y)
# data$married_0y<-as.factor(data$married_0y)
# data$parent_identity_0y<-as.factor(data$parent_identity_0y)
# data$race_ethnicity_0y<-as.factor(data$race_ethnicity_0y)


library(fastDummies)

data<-dummy_cols(data, select_columns = c('sex_0y', 'married_0y', 'race_g', 'parent_identity_0y', 'race_ethnicity_0y'))


library(learnr)
library(DiagrammeR)
library(grf)
library(tidyverse)
library(broom)
library(fastDummies)
library(lmtest)
library(rpart)
library(glmnet)
library(splines)
library(MASS)
library(sandwich)
library(ggplot2)
library(data.table)

covariates<-c('discount_rate_1y','age_0y', 'bmi_0y', 'income_0y', 
                 'high_educ_0y', 'sex_0y_F', 'vol',
                 'married_0y_2', 'married_0y_3', 'married_0y_4', 'married_0y_5', 'married_0y_6',
                 'parent_identity_0y_2','parent_identity_0y_3', 
                 'parent_identity_0y_4', 'parent_identity_0y_5',
                 'race_ethnicity_0y_2', 'race_ethnicity_0y_3', 
                 'race_ethnicity_0y_4', 'race_ethnicity_0y_5',
                 'parent_age_0y', 
                 'cpeur2', 'eaeur1', 'iqeur2',
                 'nihtbx_totalcomp_uncorrected_0y', 'history_ratio_0y',
                'lh_rostralanteriorcingulate_area._.1', 'lh_WhiteSurfArea_area._.1', 'rh_isthmuscingulate_area._.2',
              'rh_parahippocampal_area._.2', 'rh_parsopercularis_area._.2', 'rh_temporalpole_area._.2', 
              'rh_fusiform_volume._.8', 'rh_parahippocampal_volume._.8', 'rh_parsopercularis_volume._.8', 
              'Right.Caudate._.9', 'TotalGrayVol._.9', 'wm.rh.temporalpole._.18',
              'tfmri_ma_arvn_b_cds_smglh', 'tfmri_ma_arvn_b_cds_pocgerh', 'tfmri_ma_acvn_b_cds_pcelh', 
              'tfmri_ma_acvn_b_cds_prgisrh', 'tfmri_ma_acvn_b_cds_pocgerh', 'tfmri_ma_alrvn_b_cds_postcrh', 
              'tfmri_ma_alrvn_b_cds_romdfrrh', 'tfmri_ma_asrvn_b_cds_smglh', 'tfmri_ma_asrvn_b_cds_smgrh', 
              'tfmri_ma_allvn_b_cds_tvtplh', 'tfmri_ma_allvn_b_cds_ffrh', 'tfmri_ma_asvn_b_cds_smgrh', 
              'tfmri_ma_acmvn_b_scs_cbwmrh')

W = data$rh_adi_bi_0y
X = data[, covariates]
Z = data$section8_0y
n = nrow(data)


  
################## RATE: Distress Score PD 2year #######################
Y <- data[, 'distress_score_pd_2y']

train <- sample(1:n, n/2)

set.seed(123, kind = "Mersenne-Twister", normal.kind = "Inversion", sample.kind = "Rejection")
cf.priority <- instrumental_forest(
  X[train, ], Y[train], W[train], Z[train],
  num.trees = 50000, 
  tune.parameters = 'all',
  tune.num.trees = 5000,
  tune.num.reps = 250,
  tune.num.draws = 2000)

set.seed(123, kind = "Mersenne-Twister", normal.kind = "Inversion", sample.kind = "Rejection")
# Estimate AUTOC on held out data.
cf.eval <- instrumental_forest(
  X[-train, ], Y[-train], W[-train], Z[-train], 
  num.trees = 50000, 
  tune.parameters = 'all',
  tune.num.trees = 5000,
  tune.num.reps = 250,
  tune.num.draws = 2000)


set.seed(123, kind = "Mersenne-Twister", normal.kind = "Inversion", sample.kind = "Rejection")
tau.hat <- predict(cf.priority, X[-train, ])$predictions
rate <- rank_average_treatment_effect(cf.eval, tau.hat, target = "AUTOC")

est<-rate$estimate
se<-rate$std.err
tstat <- est / se
pvalue <- 2*(1-pnorm(abs(tstat)))
lowci<- est + -1 * qnorm(0.975) * se 
highci<- est + 1 * qnorm(0.975) * se 
rate.res<-cbind(est, se, tstat, pvalue, lowci, highci)
row.names(rate.res)<-'RATE: Distress PD 2y'
print(rate.res)



plot(rate, xlab = "Treated fraction", main = "TOC of Hallucination-Like Experiences (2year) evaluated on ATE estimated from 50% Sample Size") 
  
```
